{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-schema",
    "version": "17.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-schema-17.0.1.jar",
          "url": "project-schema-17.0.1.jar",
          "size": 657507,
          "sha512": "d9607f283909dc9571bceecf9890276c40c023f7bd168552de3b5acbb0f7f81443f4bbfe14ca57e526197d74486f717dafdfdf720fc0a8bc5411197f6096bd16",
          "sha256": "370e6ef0c10c650f8ca7def38b6d7f1bd4b2288f15a3d6f87364e3f029167d2c",
          "sha1": "38ff13c3896d20a7dbf920270a06a7b5aace3f4c",
          "md5": "5962b680845206c599431042f29203a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-schema-17.0.1.jar",
          "url": "project-schema-17.0.1.jar",
          "size": 657507,
          "sha512": "d9607f283909dc9571bceecf9890276c40c023f7bd168552de3b5acbb0f7f81443f4bbfe14ca57e526197d74486f717dafdfdf720fc0a8bc5411197f6096bd16",
          "sha256": "370e6ef0c10c650f8ca7def38b6d7f1bd4b2288f15a3d6f87364e3f029167d2c",
          "sha1": "38ff13c3896d20a7dbf920270a06a7b5aace3f4c",
          "md5": "5962b680845206c599431042f29203a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-schema-17.0.1-sources.jar",
          "url": "project-schema-17.0.1-sources.jar",
          "size": 92209,
          "sha512": "3f2d7006e928e9881905cc97ccc3ff1254c47d1b7401d9ce1d1803f1aff461c37fc2ee4f6c8762a407389a1b50288b4f2669c8a3e0361e30bdef9045defec6b5",
          "sha256": "f9bdddca3f61d59d469544734998877dc7b11b4b998e3cac4f81097b078d58d8",
          "sha1": "35b0cf4e81f6616b1e5895d64419ed6ff456f273",
          "md5": "cfcba2450035b0b3e0d972b8b0b83259"
        }
      ]
    }
  ]
}
