{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "15.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "15.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "15.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-15.0.0.jar",
          "url": "codegen-15.0.0.jar",
          "size": 457403,
          "sha512": "9d7d966ad9549d40be04bbaf339dffd2b2cd77a97498e07a9c6fe6be814092a72cf6b3d9011dd7055cac6bb0ba7ecdeee2e91f53154c8f95d653617279986844",
          "sha256": "da5444323f32db57af5b6eb47be47910ee8aa517be1380acb825f344d3ce9393",
          "sha1": "57e3835aa7f0f6d921147dfe2b5ac07c2b2a5bb8",
          "md5": "8f7c23168c3278a9549fcdf2585a49a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "15.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "15.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-15.0.0.jar",
          "url": "codegen-15.0.0.jar",
          "size": 457403,
          "sha512": "9d7d966ad9549d40be04bbaf339dffd2b2cd77a97498e07a9c6fe6be814092a72cf6b3d9011dd7055cac6bb0ba7ecdeee2e91f53154c8f95d653617279986844",
          "sha256": "da5444323f32db57af5b6eb47be47910ee8aa517be1380acb825f344d3ce9393",
          "sha1": "57e3835aa7f0f6d921147dfe2b5ac07c2b2a5bb8",
          "md5": "8f7c23168c3278a9549fcdf2585a49a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-15.0.0-sources.jar",
          "url": "codegen-15.0.0-sources.jar",
          "size": 92822,
          "sha512": "31361e093f15dffe5e380a4bf8dca95011fa0de7493fff3a0a16c21e67176d340dc640f7d21fbc9be8f300618c8de588d300852efa46be4c54471991017b6b27",
          "sha256": "f4785cf8e46bf26acde6d109fa2402fa560e57ef8adecd9cc06af494247b88ee",
          "sha1": "dd3f39c0ad423bc6cd5e0344e299e656b744ae1e",
          "md5": "e0cdd39e91e9b161545ba3cdd8ae46c0"
        }
      ]
    }
  ]
}
