{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-11.0.0.jar",
          "url": "codegen-11.0.0.jar",
          "size": 402740,
          "sha512": "0894ce22e3704ceb60acb17d260deb6450f1fd7cfab388c9478ad27f14d2513a8965801a6345bdfb77eeaa9700ea9ee8832042e7bb50427daa4e47e5e5f245cf",
          "sha256": "5130f5673e73efdce1971efd602c860326231508f10658c3f90e6512fbd7107d",
          "sha1": "48a4f1149c163a99f86e500f419b933e861b7a1f",
          "md5": "228ff1d4233b7dbcb3e35fe457e29bff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-11.0.0.jar",
          "url": "codegen-11.0.0.jar",
          "size": 402740,
          "sha512": "0894ce22e3704ceb60acb17d260deb6450f1fd7cfab388c9478ad27f14d2513a8965801a6345bdfb77eeaa9700ea9ee8832042e7bb50427daa4e47e5e5f245cf",
          "sha256": "5130f5673e73efdce1971efd602c860326231508f10658c3f90e6512fbd7107d",
          "sha1": "48a4f1149c163a99f86e500f419b933e861b7a1f",
          "md5": "228ff1d4233b7dbcb3e35fe457e29bff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-11.0.0-sources.jar",
          "url": "codegen-11.0.0-sources.jar",
          "size": 80674,
          "sha512": "04fc50d0ce452a4ba63681b08d2be10b515c6134ab5daf4e3935f9c8acf567536d196be51e46cb157e736a42a541439c5d0ea144c003958a9ecf305bacf30631",
          "sha256": "e33a72d536dada45159e18d193e4a78ac018c8142b879a56d5302dfd3d1f08a0",
          "sha1": "d36f5d341086c285dad227821acdfd5bd5b9526e",
          "md5": "b01d2e678291faf4d9d0f0acf875bd9f"
        }
      ]
    }
  ]
}
