{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-11.0.0.jar",
          "url": "ftc-hardware-11.0.0.jar",
          "size": 416319,
          "sha512": "a4775ee4edc6a0f567f702921c7e2184c1a1328ebcf5d98994d001634e89ab978fa6c806ccec5f7077c85e0924696ae92ff6bf04e1e1f99ea3d4c69d5ddd7ecf",
          "sha256": "7ad84dbd3ec4f0d0192352823ac85d83e7c4bf515a23d5fef2a355a56fc43bd0",
          "sha1": "a52be638560f203abfd09a73d870654bd3fd486b",
          "md5": "8e4162d0920e862bd565da6bda72475b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-11.0.0.jar",
          "url": "ftc-hardware-11.0.0.jar",
          "size": 416319,
          "sha512": "a4775ee4edc6a0f567f702921c7e2184c1a1328ebcf5d98994d001634e89ab978fa6c806ccec5f7077c85e0924696ae92ff6bf04e1e1f99ea3d4c69d5ddd7ecf",
          "sha256": "7ad84dbd3ec4f0d0192352823ac85d83e7c4bf515a23d5fef2a355a56fc43bd0",
          "sha1": "a52be638560f203abfd09a73d870654bd3fd486b",
          "md5": "8e4162d0920e862bd565da6bda72475b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-11.0.0-sources.jar",
          "url": "ftc-hardware-11.0.0-sources.jar",
          "size": 156684,
          "sha512": "05aa85eeeba49d7f9ec5e5723a60da95246f787d9148ebd8b10d31b912106fdc6f8589dcc485be5965c09ef092e706f35d7f8dee3b4cc61124b61c470d4706a2",
          "sha256": "5c72a2ae0a95b4465bb784c01c4ac6523a0142a86bbfb68442d96929f9778c8d",
          "sha1": "188a4d0d93b9aaa15cd0cef45cfa4a50b74eeb5c",
          "md5": "d77efe0115dbb7e2964aa2dc2cb14fff"
        }
      ]
    }
  ]
}
