{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "19.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-19.1.1.jar",
          "url": "simulation-foundation-19.1.1.jar",
          "size": 36134,
          "sha512": "6868e805f069bbfd11970d299d348ef21f0d7258faebd208bc055c48669783a0240abe7eec5b9f5a3cde9141e7a0921454415a1dd1c5fbe120eed4ed97cb0d3b",
          "sha256": "3644ce2cce7d9f168d9691b678987a73c2edb54d58ff0d0c2f81a3a01e180155",
          "sha1": "4d463f286d5ca9b4f1a6d53eeda163941cf793bd",
          "md5": "c9b1b305c9aea5d33098d220edcb1fcf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.1.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-19.1.1.jar",
          "url": "simulation-foundation-19.1.1.jar",
          "size": 36134,
          "sha512": "6868e805f069bbfd11970d299d348ef21f0d7258faebd208bc055c48669783a0240abe7eec5b9f5a3cde9141e7a0921454415a1dd1c5fbe120eed4ed97cb0d3b",
          "sha256": "3644ce2cce7d9f168d9691b678987a73c2edb54d58ff0d0c2f81a3a01e180155",
          "sha1": "4d463f286d5ca9b4f1a6d53eeda163941cf793bd",
          "md5": "c9b1b305c9aea5d33098d220edcb1fcf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-19.1.1-sources.jar",
          "url": "simulation-foundation-19.1.1-sources.jar",
          "size": 8970,
          "sha512": "c6d72023005ff7bfc075705cb7bf44efb1a6ff7b07a8cab64044077803f602d32ed49344911a05617765cb03c67de6390b4f077f7d4f409c33a809f1874dc2e0",
          "sha256": "48508ecb6ddd32515437f0b40037e83fd89e02883f54497ae0e162bf48443bf9",
          "sha1": "cfb0cfbc257cfea3fa7cf0635986f122b5424e82",
          "md5": "ff8c9b64be62cfcafe822f11337096f6"
        }
      ]
    }
  ]
}
