{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-mocks",
    "version": "13.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "13.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-13.0.0.jar",
          "url": "ftc-mocks-13.0.0.jar",
          "size": 168777,
          "sha512": "e424af094ad36433bb48acb6015d6b768d86639080b20abbb73197b1c2755937af768e1d3ddd04aeaf5ab87f8dd84a17c29a53f31aa7b36046ec31b752e92e18",
          "sha256": "86ae90f80de361a4edbfb74565903542f67fd5657c35e46dccfaa02e42b85100",
          "sha1": "233250636533eda6f6333a543d93ed2acba839c4",
          "md5": "99f34d6324130c2b07d3f4145fa5faf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "13.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-13.0.0.jar",
          "url": "ftc-mocks-13.0.0.jar",
          "size": 168777,
          "sha512": "e424af094ad36433bb48acb6015d6b768d86639080b20abbb73197b1c2755937af768e1d3ddd04aeaf5ab87f8dd84a17c29a53f31aa7b36046ec31b752e92e18",
          "sha256": "86ae90f80de361a4edbfb74565903542f67fd5657c35e46dccfaa02e42b85100",
          "sha1": "233250636533eda6f6333a543d93ed2acba839c4",
          "md5": "99f34d6324130c2b07d3f4145fa5faf9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-mocks-13.0.0-sources.jar",
          "url": "ftc-mocks-13.0.0-sources.jar",
          "size": 39542,
          "sha512": "abeddd0ae576f6b6c421bbd5af495b773331343a29f3a313a03728de0360f60fcb61851bfc1b4474aee522909e7f177d940e84e57508da7d545883bc75f3fdfd",
          "sha256": "2b65cde412926454d7907c79c9ddf6b454aa2ff77a1d78b9faa919fac276bd60",
          "sha1": "b7b9e32593c9d08199b101089812e86153401203",
          "md5": "624c595579b53443df0db853b7429218"
        }
      ]
    }
  ]
}
