{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-mocks",
    "version": "17.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-17.0.1.jar",
          "url": "ftc-mocks-17.0.1.jar",
          "size": 174188,
          "sha512": "318535ad53540220286e94b7f2314ffb6f74177f0e40c408ba1339f8ef71490238e83f521df9fcfa1518484c64b139e7573e68e39b99112ba0943717b81acfd4",
          "sha256": "20d378e2c333ce82b1ae6bf79f6587a44b64b8a60fcca5844e33d3c5d5e3f3cc",
          "sha1": "eb4459629c0d0a639ad082dce701e1abb84a2104",
          "md5": "d3fef448bac4b367d8e300c06fee8e5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-17.0.1.jar",
          "url": "ftc-mocks-17.0.1.jar",
          "size": 174188,
          "sha512": "318535ad53540220286e94b7f2314ffb6f74177f0e40c408ba1339f8ef71490238e83f521df9fcfa1518484c64b139e7573e68e39b99112ba0943717b81acfd4",
          "sha256": "20d378e2c333ce82b1ae6bf79f6587a44b64b8a60fcca5844e33d3c5d5e3f3cc",
          "sha1": "eb4459629c0d0a639ad082dce701e1abb84a2104",
          "md5": "d3fef448bac4b367d8e300c06fee8e5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-mocks-17.0.1-sources.jar",
          "url": "ftc-mocks-17.0.1-sources.jar",
          "size": 40500,
          "sha512": "eeaa6393b4ee00a56f051981bc1b52586699e391392092035473ea0f877b6e47eab7761a56ca9440fabd8c394cac1539894160748846653dee28f31c108ea09b",
          "sha256": "eeef4d6b10479783b033d674541d7e423c326c98c74cec0b23cdfbf96bf9ae3a",
          "sha1": "8a7f66818b25af0986ddca6e003acb2bd33b9773",
          "md5": "60587971d71f268638d2639577a7e68b"
        }
      ]
    }
  ]
}
