{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-model",
    "version": "15.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "15.0.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "15.0.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-15.0.3.jar",
          "url": "project-model-15.0.3.jar",
          "size": 69235,
          "sha512": "8ed1d63260a4caeb265ff941fa318f0addc09f1bfdcb0ccbcaa587572351438798058766117716931eb91815fce39893194274ab81d3bb5e8c9a45c0fdac46a9",
          "sha256": "7b8c483d1792ee22e3527a1b3070dafdce88500774975d05f270030593602a88",
          "sha1": "c47f01b8579585d051e0254af103c450ab560bea",
          "md5": "cb22d7e1f7413769a1e0e3f71dc70dfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "15.0.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "15.0.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-15.0.3.jar",
          "url": "project-model-15.0.3.jar",
          "size": 69235,
          "sha512": "8ed1d63260a4caeb265ff941fa318f0addc09f1bfdcb0ccbcaa587572351438798058766117716931eb91815fce39893194274ab81d3bb5e8c9a45c0fdac46a9",
          "sha256": "7b8c483d1792ee22e3527a1b3070dafdce88500774975d05f270030593602a88",
          "sha1": "c47f01b8579585d051e0254af103c450ab560bea",
          "md5": "cb22d7e1f7413769a1e0e3f71dc70dfc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-model-15.0.3-sources.jar",
          "url": "project-model-15.0.3-sources.jar",
          "size": 11701,
          "sha512": "dc469df31d0b1882cbcbf25b80161698ba66cae8f94e7eba996bc46914583ac54d40440ca04a1e05fcc926c676d245d0a18dd2870916fc7b91c018e232ec0de8",
          "sha256": "b36c22bf8a59661943708a7c26f4baf8d0b2e187a9162a501cfdf4fdc48a6020",
          "sha1": "17b7aeceaa0ed9c60c517cf3ab7244cc5c17f6ee",
          "md5": "b57008f682403adbd6b92b0e2043a4b2"
        }
      ]
    }
  ]
}
