{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "19.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-19.1.3.jar",
          "url": "codegen-19.1.3.jar",
          "size": 476197,
          "sha512": "972486ea359499b110510c61e203fddaf1042219879450a7779d2a3f9bdbbe1d5ae509ebcc1499516790018b0f470f992b48f07b44c26d5da02b4cbfa41aa486",
          "sha256": "9fa2eb2db59d069e60cf73c5bd9ba15710ea01164be6af377c721e2aed761630",
          "sha1": "f7f4bd9b2b8a836a5751350484f5a559000b6710",
          "md5": "37d45f42a4213d72004d2403ad43afbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-19.1.3.jar",
          "url": "codegen-19.1.3.jar",
          "size": 476197,
          "sha512": "972486ea359499b110510c61e203fddaf1042219879450a7779d2a3f9bdbbe1d5ae509ebcc1499516790018b0f470f992b48f07b44c26d5da02b4cbfa41aa486",
          "sha256": "9fa2eb2db59d069e60cf73c5bd9ba15710ea01164be6af377c721e2aed761630",
          "sha1": "f7f4bd9b2b8a836a5751350484f5a559000b6710",
          "md5": "37d45f42a4213d72004d2403ad43afbd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-19.1.3-sources.jar",
          "url": "codegen-19.1.3-sources.jar",
          "size": 99474,
          "sha512": "ce2c9c8822ca435be95acbe1ee1c0bcc7dd819386ad3b7bb156069dec4cce0ead5556a8f23cba7004e56b9bbba0d50053eab654471e9a7f5835b7e1e1a0b4650",
          "sha256": "369783828742b66e1a4f9cf54c31f947e7d1c0c8b8cc38c9356b312609294fb5",
          "sha1": "9a3e494b7ae909d313d8f30636d05ed8dcbc4733",
          "md5": "67361765bf798c91084a6ca70abedec0"
        }
      ]
    }
  ]
}
