{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-windows",
    "version": "14.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "14.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-14.0.0.jar",
          "url": "simulator-runtime-windows-14.0.0.jar",
          "size": 5077,
          "sha512": "4206a5b01422977b514a15ee81241084956fd787615fb0d43bf39d525a4839d38831c1103c42c03bf01a8a38d6b6971492df248d07a1e83d7946fb99ea098143",
          "sha256": "c149fd412f06fac2dfaf27336bd79c7b8373bd50e42f803dc2d4c385d9073155",
          "sha1": "d74bb3b8d6dcd9317fa475851ea887a7e921137b",
          "md5": "fe953a3f5a3f349fdc0ddddb78472549"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "14.0.0"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-14.0.0.jar",
          "url": "simulator-runtime-windows-14.0.0.jar",
          "size": 5077,
          "sha512": "4206a5b01422977b514a15ee81241084956fd787615fb0d43bf39d525a4839d38831c1103c42c03bf01a8a38d6b6971492df248d07a1e83d7946fb99ea098143",
          "sha256": "c149fd412f06fac2dfaf27336bd79c7b8373bd50e42f803dc2d4c385d9073155",
          "sha1": "d74bb3b8d6dcd9317fa475851ea887a7e921137b",
          "md5": "fe953a3f5a3f349fdc0ddddb78472549"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-windows-14.0.0-sources.jar",
          "url": "simulator-runtime-windows-14.0.0-sources.jar",
          "size": 5077,
          "sha512": "cd7ff02a86975c2bda24cb130fea160591a5fe4481df49ffff028ab703d1c75d373cb6d718d7800511770cf6b5cb1dd14048d8bca6e48f1c6a68298934d56b5b",
          "sha256": "f01b3cf6e2f63f0787c08b3716a96531c18a5fab48ca4684d5fc58b3839d2f12",
          "sha1": "5f6102e1bd25219e10259bd637af398fe20e9ba0",
          "md5": "22ec3c4ea777412f1c80cc614be6c415"
        }
      ]
    }
  ]
}
