{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "14.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "14.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "14.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "14.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-14.0.0.jar",
          "url": "codegen-14.0.0.jar",
          "size": 449420,
          "sha512": "051a68c231a0baa2171514b38030062699f057c3fac98bd33d0936f589aec577a2ab09bef1604a4921cfd4579a265d07a974890059fc0b82f31957f62363bd36",
          "sha256": "6f3fc19fc7a3e90b818a17bc5e95108be6e1ee94989aad8d0491c929ef3a8258",
          "sha1": "8523472e232069f9ef618d35d093c510ee9a2621",
          "md5": "fd7ea57c2c78a7951820eb8d0c62deb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "14.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "14.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "14.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-14.0.0.jar",
          "url": "codegen-14.0.0.jar",
          "size": 449420,
          "sha512": "051a68c231a0baa2171514b38030062699f057c3fac98bd33d0936f589aec577a2ab09bef1604a4921cfd4579a265d07a974890059fc0b82f31957f62363bd36",
          "sha256": "6f3fc19fc7a3e90b818a17bc5e95108be6e1ee94989aad8d0491c929ef3a8258",
          "sha1": "8523472e232069f9ef618d35d093c510ee9a2621",
          "md5": "fd7ea57c2c78a7951820eb8d0c62deb7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-14.0.0-sources.jar",
          "url": "codegen-14.0.0-sources.jar",
          "size": 91891,
          "sha512": "f708df1408116d9db747c63a188a6ef65a780e80bfd3153eede6a322bed7506091e0fa715b4e0648825bd7c42d45de328e760f02fd2207b03d08e2be1c2e8b01",
          "sha256": "4dce3a962c70671bc9d66c1f22eca8198b0763e0614929e4893969c33643b395",
          "sha1": "7abfb32008366bfcd2e02b7888746f36623f9356",
          "md5": "1a9e6ab6bbc0e1f96364234e560fc00d"
        }
      ]
    }
  ]
}
