{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "telemetry-schema",
    "version": "16.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-schema-16.0.1.jar",
          "url": "telemetry-schema-16.0.1.jar",
          "size": 36827,
          "sha512": "96a007d5f549710e5bc94867a0dfe08b8223dd52340832c55cb431e7bfb864fae492dd1c21871762e5529d4a95cde7d5686ffc170f949328ae40163bec6bab57",
          "sha256": "34b7cac1fb8e15ce411a3dc5b8f350a0a78734fbacfff183515bdd591dbe2e40",
          "sha1": "35035d45ecb745cdae052d5ac93b522d8b531acf",
          "md5": "4b340308ee6dbb38d01d95d4f0b2f428"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-schema-16.0.1.jar",
          "url": "telemetry-schema-16.0.1.jar",
          "size": 36827,
          "sha512": "96a007d5f549710e5bc94867a0dfe08b8223dd52340832c55cb431e7bfb864fae492dd1c21871762e5529d4a95cde7d5686ffc170f949328ae40163bec6bab57",
          "sha256": "34b7cac1fb8e15ce411a3dc5b8f350a0a78734fbacfff183515bdd591dbe2e40",
          "sha1": "35035d45ecb745cdae052d5ac93b522d8b531acf",
          "md5": "4b340308ee6dbb38d01d95d4f0b2f428"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "telemetry-schema-16.0.1-sources.jar",
          "url": "telemetry-schema-16.0.1-sources.jar",
          "size": 9733,
          "sha512": "aeb145e6d9119188400294937c2738e2679b70017dc85c1fdecf8a514c531c48ac03c3e6f336868be78a2b97bcd01a84e2f82e6ac307eaba7f68073a041ef683",
          "sha256": "df87f01c9689a02795e73c9289267cefbed48a75c06ee0f5a42b6138727ddf91",
          "sha1": "9daa34a46c58a16568d10b5a52f308590b24f222",
          "md5": "70fee2efedecd624c842f409b44b7440"
        }
      ]
    }
  ]
}
