{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator",
    "version": "17.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-hardware",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-mocks",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-17.0.1.jar",
          "url": "simulator-17.0.1.jar",
          "size": 209874,
          "sha512": "572214695fd75fa9458b05afde954e8849df2e1caef8b3f5635ee6b726fc31106e08c3795b2c80abf4d8caa29b38bc5c474ff9db3c77f7b983da7cbc2bd59907",
          "sha256": "4daa63645350c9cead5941d774f6450192c1f6853b6d488448fa5b2fe682c0e2",
          "sha1": "91d7865751ebc953419a77892fd3a209ecd71af6",
          "md5": "a23c98d5fc8b83975b068792b2a016ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.dyn4j",
          "module": "dyn4j",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.18"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-hardware",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-mocks",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-17.0.1.jar",
          "url": "simulator-17.0.1.jar",
          "size": 209874,
          "sha512": "572214695fd75fa9458b05afde954e8849df2e1caef8b3f5635ee6b726fc31106e08c3795b2c80abf4d8caa29b38bc5c474ff9db3c77f7b983da7cbc2bd59907",
          "sha256": "4daa63645350c9cead5941d774f6450192c1f6853b6d488448fa5b2fe682c0e2",
          "sha1": "91d7865751ebc953419a77892fd3a209ecd71af6",
          "md5": "a23c98d5fc8b83975b068792b2a016ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-17.0.1-sources.jar",
          "url": "simulator-17.0.1-sources.jar",
          "size": 72081,
          "sha512": "7ad9d023ecd4a7f627018b5163940e681a0c0ee64fe4d2a4a4f359c9598dfdf72bbf63a147080e9196893e2ce81808888d98bb9b07fb6bd2df7c34dbeeecc45b",
          "sha256": "ba5151751d09138d60c670304dd30b5e67842976da3a5d0eae947c71f54abb80",
          "sha1": "e3c4d82016f5bc83c4e7c43352905e953d03ec23",
          "md5": "f33b6637b5a66835aa95985ad1c7f984"
        }
      ]
    }
  ]
}
