{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "19.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.0.5"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "19.0.5"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "19.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-19.0.5.jar",
          "url": "codegen-19.0.5.jar",
          "size": 476145,
          "sha512": "df1e356825211f9875285bee148dda13f85f70b825e731d61e8b3ff34f912e017d8917d77188476b86d6175e4d1f8c165ae6384ca7f2702e5e39727b104428c5",
          "sha256": "37c23daad021fc58ab8f381e4f9a2074c08eaec7b262fc188c9de25569c318bd",
          "sha1": "af8719c7bdeae65bc3539e5183ad8cded73e89d8",
          "md5": "99b6a4f8ba3e1a549db8d4059eeb77e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.0.5"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "19.0.5"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "19.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-19.0.5.jar",
          "url": "codegen-19.0.5.jar",
          "size": 476145,
          "sha512": "df1e356825211f9875285bee148dda13f85f70b825e731d61e8b3ff34f912e017d8917d77188476b86d6175e4d1f8c165ae6384ca7f2702e5e39727b104428c5",
          "sha256": "37c23daad021fc58ab8f381e4f9a2074c08eaec7b262fc188c9de25569c318bd",
          "sha1": "af8719c7bdeae65bc3539e5183ad8cded73e89d8",
          "md5": "99b6a4f8ba3e1a549db8d4059eeb77e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-19.0.5-sources.jar",
          "url": "codegen-19.0.5-sources.jar",
          "size": 99457,
          "sha512": "b4d8a06ea68d11e86a99118ea50e33ce480d2a95a2a850e667e415c5a1924174a5992761f015847c7cb087d8d5f9a652ab5c50d8ff8eacf27a44ffa601297fcb",
          "sha256": "f85281d59053d9444159b1676c971ef40c786e561eed5ede17b284e0873c28e0",
          "sha1": "8a53759bc855a8894526192fafa36edde58828be",
          "md5": "b30ac08468ff8cdf038ea855e2277352"
        }
      ]
    }
  ]
}
