{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "13.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "13.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "13.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "13.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-13.0.0.jar",
          "url": "codegen-13.0.0.jar",
          "size": 442411,
          "sha512": "f2354997f4c2322aa8920c3f7fae8b517abbe266519dcc0dbac86c23087f4c48b94f86f0cf3362626607a8558332a2631c021dbd5973b071743c4cab8e54749f",
          "sha256": "dbd12f910934d80155d495472f3896e7fc358cc77bf36b3d0d66097941cc52d7",
          "sha1": "d098ea0b0d58c1d34bed00ccd7c92350c7295fe6",
          "md5": "842fad95babf21185c31ec8a06925b1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "13.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "13.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "13.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-13.0.0.jar",
          "url": "codegen-13.0.0.jar",
          "size": 442411,
          "sha512": "f2354997f4c2322aa8920c3f7fae8b517abbe266519dcc0dbac86c23087f4c48b94f86f0cf3362626607a8558332a2631c021dbd5973b071743c4cab8e54749f",
          "sha256": "dbd12f910934d80155d495472f3896e7fc358cc77bf36b3d0d66097941cc52d7",
          "sha1": "d098ea0b0d58c1d34bed00ccd7c92350c7295fe6",
          "md5": "842fad95babf21185c31ec8a06925b1d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-13.0.0-sources.jar",
          "url": "codegen-13.0.0-sources.jar",
          "size": 90368,
          "sha512": "2e60f2d04e26038fbf1eed5c69bbcb49ad94acd1f2e3b4e2812ebf301be817698722764ee5eae80d8cd4817fb5610acf7d7d79a0d2a5fb52deaa6d674a0b4d23",
          "sha256": "06c0fe418ea3b325c69b693796cd1979a9cc3a48e06f9810ad7c49ae3a109941",
          "sha1": "0c79e34514fc1c13ba67a7d15028621e91a70d17",
          "md5": "100741e853804e1c318bd186a008191a"
        }
      ]
    }
  ]
}
