{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-windows",
    "version": "19.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "19.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-19.1.4.jar",
          "url": "simulator-runtime-windows-19.1.4.jar",
          "size": 5077,
          "sha512": "a79483a1ef9f31357744fdd78ce0ec4b02a50f9a07d8d40198a60acbd6a3925158acc67d85d565c3edd64db945b3a28c14ca3760a89506d415a00ba920375eb5",
          "sha256": "f8aa8d4a5cc975b0458ec5a92849996c8135514472be022ca124dc9cdc5c2ea4",
          "sha1": "d3eccef75b2ae28ce4f5097c786a70cd559cb909",
          "md5": "71c07e179728f6d334a5c566fe5bb846"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "19.1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-19.1.4.jar",
          "url": "simulator-runtime-windows-19.1.4.jar",
          "size": 5077,
          "sha512": "a79483a1ef9f31357744fdd78ce0ec4b02a50f9a07d8d40198a60acbd6a3925158acc67d85d565c3edd64db945b3a28c14ca3760a89506d415a00ba920375eb5",
          "sha256": "f8aa8d4a5cc975b0458ec5a92849996c8135514472be022ca124dc9cdc5c2ea4",
          "sha1": "d3eccef75b2ae28ce4f5097c786a70cd559cb909",
          "md5": "71c07e179728f6d334a5c566fe5bb846"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-windows-19.1.4-sources.jar",
          "url": "simulator-runtime-windows-19.1.4-sources.jar",
          "size": 5077,
          "sha512": "d651b6f13a9eb60391b541cb0374ed23070b9270956770f5450a222fdc01d8d83798954f56fabea557102282257987d3f65d03528771ad4e3a624f4e87369548",
          "sha256": "b96be8b8ff6db657b767bde68f6f3e0073d53ea897225bdb3f28eb8fd26c23ef",
          "sha1": "310fd821f6c57299a17627115f8094bb876a6891",
          "md5": "2caedee248d10eb5edd658d9b38abdb2"
        }
      ]
    }
  ]
}
