{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-windows",
    "version": "16.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "16.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-16.0.1.jar",
          "url": "simulator-runtime-windows-16.0.1.jar",
          "size": 5077,
          "sha512": "fede8fc4a14e90653a6cd1dc9a54b10dc79e974405b721d1f1aa542806d68ae405c5584512d6356e4080ac4674f876534a1c525261ae76b9208d96aa7edc7f0c",
          "sha256": "444c3a3b4055ad0de61fb9eefdc09a689b36bf5b237482ee358ab77156b5dae8",
          "sha1": "c5efd43bbc8429e7a74544f2c15d23ffc1400191",
          "md5": "ddfd5c57c794c59247545b9538ca17f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-16.0.1.jar",
          "url": "simulator-runtime-windows-16.0.1.jar",
          "size": 5077,
          "sha512": "fede8fc4a14e90653a6cd1dc9a54b10dc79e974405b721d1f1aa542806d68ae405c5584512d6356e4080ac4674f876534a1c525261ae76b9208d96aa7edc7f0c",
          "sha256": "444c3a3b4055ad0de61fb9eefdc09a689b36bf5b237482ee358ab77156b5dae8",
          "sha1": "c5efd43bbc8429e7a74544f2c15d23ffc1400191",
          "md5": "ddfd5c57c794c59247545b9538ca17f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-windows-16.0.1-sources.jar",
          "url": "simulator-runtime-windows-16.0.1-sources.jar",
          "size": 5077,
          "sha512": "15ee584035d0111219648727fa34f7b30fc40937a3c018c1354d469d824837109a1a7172159c8e3573f94d888dd647e61e7f417b27f169d027f7c983df0739d5",
          "sha256": "37741eedf94c0f5342598b5b7ab487595e1f04b29b487bbe48b6000cdb83c697",
          "sha1": "db89fbb290d21674342d9d0df9c0e0c91e2fd107",
          "md5": "d0cfa8003dc1e609bcd28cf87ec4131b"
        }
      ]
    }
  ]
}
