{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-11.0.0.jar",
          "url": "simulation-foundation-11.0.0.jar",
          "size": 46300,
          "sha512": "7a1135e3eef47c43400ca44b98fb44ec2e811f089525e679a28f662050cdfcea43c0b4f82352f7e7c73b02bad19a3c0cabd264261100a4b14856c4c9a490ab7f",
          "sha256": "73be4fe5354527e48bad13e16cdbce62f9b24a6552af7b9853c57691b45ea9b0",
          "sha1": "34acbe58978b9e93297885c6c4ad6b25a71afc53",
          "md5": "c9cdde94d6aba9adc0bdd8fbccd023da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-11.0.0.jar",
          "url": "simulation-foundation-11.0.0.jar",
          "size": 46300,
          "sha512": "7a1135e3eef47c43400ca44b98fb44ec2e811f089525e679a28f662050cdfcea43c0b4f82352f7e7c73b02bad19a3c0cabd264261100a4b14856c4c9a490ab7f",
          "sha256": "73be4fe5354527e48bad13e16cdbce62f9b24a6552af7b9853c57691b45ea9b0",
          "sha1": "34acbe58978b9e93297885c6c4ad6b25a71afc53",
          "md5": "c9cdde94d6aba9adc0bdd8fbccd023da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-11.0.0-sources.jar",
          "url": "simulation-foundation-11.0.0-sources.jar",
          "size": 11388,
          "sha512": "ab0891713a12febd624adc48d10af5ccdd66438e2f784cb32dc45c2b04ae91d740c4870e200cc2c716e98e50162e74be42261782fb259075400ea047ca47f174",
          "sha256": "db929289954264467c9f4677af52114e8ed8ba95b9e6781dbb716eb4bc27556a",
          "sha1": "d418a33c5f44f7dc8156118bee47395bc89475e1",
          "md5": "6d44ed9716c1fedcb5218c10e088d58e"
        }
      ]
    }
  ]
}
