{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "frc-hardware",
    "version": "17.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "frc-runtime",
          "version": {
            "requires": "17.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "frc-hardware-17.0.1.jar",
          "url": "frc-hardware-17.0.1.jar",
          "size": 85034,
          "sha512": "8820c93d07c5afcfdf16e93d7cce10f461f93606cfbb6bbb01972397100130c21eff2647377adb75ed9b76fb8b7a7e6281819c6f15c737cda31f67cf03d43b73",
          "sha256": "d83342e40ddc8158e7b1e25f0136d5439501c09cc5482f3d8ad2a45e54d351f6",
          "sha1": "364d2c13d1c75cd0af72105ea2c1898f0d08221a",
          "md5": "fcc396df50bf5062a6f4ad7fc7cfaa1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "frc-runtime",
          "version": {
            "requires": "17.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "frc-hardware-17.0.1.jar",
          "url": "frc-hardware-17.0.1.jar",
          "size": 85034,
          "sha512": "8820c93d07c5afcfdf16e93d7cce10f461f93606cfbb6bbb01972397100130c21eff2647377adb75ed9b76fb8b7a7e6281819c6f15c737cda31f67cf03d43b73",
          "sha256": "d83342e40ddc8158e7b1e25f0136d5439501c09cc5482f3d8ad2a45e54d351f6",
          "sha1": "364d2c13d1c75cd0af72105ea2c1898f0d08221a",
          "md5": "fcc396df50bf5062a6f4ad7fc7cfaa1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "frc-hardware-17.0.1-sources.jar",
          "url": "frc-hardware-17.0.1-sources.jar",
          "size": 40419,
          "sha512": "58e5f21279476482d8da30f6dc3a2732a3bea78ccb567ba38fe3ed8be5342982a3de7772bcdcdd3d001284128d9d031a614038e63a6bfb9c35fc45ced94b44b4",
          "sha256": "fc8b5f5466919ba5264cbd83ab5ad1f1dce645264c40f1bb0042ea67eabef165",
          "sha1": "7f0bb8c7263b6b1a29b93a0f9a1bc04bd7b138ab",
          "md5": "3731044b3404dee619570f44112ecba1"
        }
      ]
    }
  ]
}
