{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-linux",
    "version": "13.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-13.0.1.jar",
          "url": "simulator-runtime-linux-13.0.1.jar",
          "size": 5077,
          "sha512": "d78953fd6a1f3df46283d969e81a105eba5ab2cdee5257627caa9952645191cca80e37429fa1bed459215fd242c7dcf180a0218171eb1564fbaee7673c9488dc",
          "sha256": "42159b547e55c25b978f3a69a5b699b89cc66eb342b47acd062c8b6c8050151e",
          "sha1": "e0bf62d22f7336d3ed4c290e848fe11900f766c6",
          "md5": "f05f00041f0eedb004f4de84ef200a2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-13.0.1.jar",
          "url": "simulator-runtime-linux-13.0.1.jar",
          "size": 5077,
          "sha512": "d78953fd6a1f3df46283d969e81a105eba5ab2cdee5257627caa9952645191cca80e37429fa1bed459215fd242c7dcf180a0218171eb1564fbaee7673c9488dc",
          "sha256": "42159b547e55c25b978f3a69a5b699b89cc66eb342b47acd062c8b6c8050151e",
          "sha1": "e0bf62d22f7336d3ed4c290e848fe11900f766c6",
          "md5": "f05f00041f0eedb004f4de84ef200a2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-linux-13.0.1-sources.jar",
          "url": "simulator-runtime-linux-13.0.1-sources.jar",
          "size": 5077,
          "sha512": "1d40351cb307839d6a0e48e13a17fb55defba9d32560cb0ce4da2c4098f06746a0921e690b1a87b1bf4035ea954eb5c9dbfcec15affc594131ba42805d35bd22",
          "sha256": "d697ac344b7686d3cee72f3a96c16850a8a06196fa6ddee03ec5b2a1d17c7c8b",
          "sha1": "7844f2bb3a7c5cc4e75cfe7f15cb2a15a3cf10c3",
          "md5": "f3c1399afc158afb143857ab48aafa80"
        }
      ]
    }
  ]
}
