{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-model",
    "version": "12.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-12.0.0.jar",
          "url": "project-model-12.0.0.jar",
          "size": 69699,
          "sha512": "f25cf56ae89c16dfffc322623641e57efda01b18be1ccdaeef15ab3a66a0a48eecc5192f36d3988d1173cc44b1dc600e9c88445571b0277d70a7eb1eefd8ec34",
          "sha256": "c0097272ab402e524c68ee2e5007d45adf86fd82ff52c07e37799c4716d0ef54",
          "sha1": "a0242a8e796704f3aa9ba7ed0518f1def2bcd59d",
          "md5": "e0806299d3fbae97e8f918fa178d6f0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-12.0.0.jar",
          "url": "project-model-12.0.0.jar",
          "size": 69699,
          "sha512": "f25cf56ae89c16dfffc322623641e57efda01b18be1ccdaeef15ab3a66a0a48eecc5192f36d3988d1173cc44b1dc600e9c88445571b0277d70a7eb1eefd8ec34",
          "sha256": "c0097272ab402e524c68ee2e5007d45adf86fd82ff52c07e37799c4716d0ef54",
          "sha1": "a0242a8e796704f3aa9ba7ed0518f1def2bcd59d",
          "md5": "e0806299d3fbae97e8f918fa178d6f0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-model-12.0.0-sources.jar",
          "url": "project-model-12.0.0-sources.jar",
          "size": 11924,
          "sha512": "1b4232c344ce6d02ee02bd73100c4593130d56a541c6e69d6eda438eb45c862b84809dfc31e56e5eb7a2c15dd7b52e99719582dd036b37302533b37dd4a804a6",
          "sha256": "01e06e78ea5cad77fed4b89c73bd0a3f3b10732b1d9b93bc72cec1f58ed33452",
          "sha1": "b7f87daecc62c6a11c9987b434cb796ef0796ffd",
          "md5": "361d6bfd82de75cae5a3b05f29b9b855"
        }
      ]
    }
  ]
}
