{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-model",
    "version": "14.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "14.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "14.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "14.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-14.0.0.jar",
          "url": "project-model-14.0.0.jar",
          "size": 69235,
          "sha512": "354f980f105b7cc6382c3fca0dcd8777c44141be8e5981bc7039e6d5bb55c1740cc4071ca534cb9c6d671a9b936fc1919c6f15626bab1b5bcb44e8057d64b4b1",
          "sha256": "0dfa80caa52d549a00d93fe6816e9da75bec1540743f7cd6fb4892e804a62400",
          "sha1": "b7312a06e5e82fcfd8ecf95391c8ec1a9e707aad",
          "md5": "2400f43d52f3ce428aea9f96c8e9d8cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "14.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "14.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "14.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-14.0.0.jar",
          "url": "project-model-14.0.0.jar",
          "size": 69235,
          "sha512": "354f980f105b7cc6382c3fca0dcd8777c44141be8e5981bc7039e6d5bb55c1740cc4071ca534cb9c6d671a9b936fc1919c6f15626bab1b5bcb44e8057d64b4b1",
          "sha256": "0dfa80caa52d549a00d93fe6816e9da75bec1540743f7cd6fb4892e804a62400",
          "sha1": "b7312a06e5e82fcfd8ecf95391c8ec1a9e707aad",
          "md5": "2400f43d52f3ce428aea9f96c8e9d8cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-model-14.0.0-sources.jar",
          "url": "project-model-14.0.0-sources.jar",
          "size": 11701,
          "sha512": "5ac0c98051512b04c22d75c01ff5e9d49bf1048682c296d8991633844a23ae39f1c62534fa8048f055c4cf30c3a1ed7dee1d7cddbaa2c177e634db9c6fdaa15a",
          "sha256": "6247512b0cd70799a587493d014ef3707ef9c5d38681a6c9ac7160b291506132",
          "sha1": "1521e23581acac3f50e07c3212bd5dba5333f911",
          "md5": "d5cae636358ff353723e72ce09344bb6"
        }
      ]
    }
  ]
}
