{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "xrp-hardware",
    "version": "19.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "telemetry-schema",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "xrp-hardware-19.1.3.jar",
          "url": "xrp-hardware-19.1.3.jar",
          "size": 34318,
          "sha512": "938021904c56d9ea31ea2da5b2d8762f1cf204fd7850b8ad4d8703be857a357c84f064f566ff9d8db6b9d08d17158d8ca0730a5e2c0023a369bef017991eb91a",
          "sha256": "7cae7daaf92d4d850b1b578c1852b65ca36a2be6d26ef982394a6c8087b290fe",
          "sha1": "a4f9ea842fde525fc5aebe5a939db2773193ef4c",
          "md5": "d763a1af1e06ad49146ef7e2e56b1052"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "telemetry-schema",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.1.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "xrp-hardware-19.1.3.jar",
          "url": "xrp-hardware-19.1.3.jar",
          "size": 34318,
          "sha512": "938021904c56d9ea31ea2da5b2d8762f1cf204fd7850b8ad4d8703be857a357c84f064f566ff9d8db6b9d08d17158d8ca0730a5e2c0023a369bef017991eb91a",
          "sha256": "7cae7daaf92d4d850b1b578c1852b65ca36a2be6d26ef982394a6c8087b290fe",
          "sha1": "a4f9ea842fde525fc5aebe5a939db2773193ef4c",
          "md5": "d763a1af1e06ad49146ef7e2e56b1052"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xrp-hardware-19.1.3-sources.jar",
          "url": "xrp-hardware-19.1.3-sources.jar",
          "size": 12214,
          "sha512": "3ad76cdb319eb9fb5a986a76e9e806bff3d68c644121be3e408b7e7ce620702bba7c43306d244ea57df728978a79d17b8fc4246a0b668da84e51a7caf74d03df",
          "sha256": "4071bd04979c44cac7a8ed185585dad1baa3e592801b639fed2b43855f692e08",
          "sha1": "aec0ff8b32e92a69daf74e42105f05c8f6bd2b8b",
          "md5": "03ca3920007f7fa31cab86a3f3f96f23"
        }
      ]
    }
  ]
}
