{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "17.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "17.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-17.0.2.jar",
          "url": "simulation-foundation-17.0.2.jar",
          "size": 36134,
          "sha512": "fceaddf81fcef5921850c8ec456fef38188c7a26379729ffda0d3d3c386e4786f290ccad13ab6a30fac03dd904f47c91d78e3206e1b95219a2f115dbb7c5d924",
          "sha256": "333a864cf521daf369d1b20ecc0ff17057277cb54e05e454b3a66bf8d7435db8",
          "sha1": "b2a2d191bf58b507ca7b8cd2e0784ea9f0f10b2f",
          "md5": "c0d13b3db7c5ad887223dafcc5b0fb5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "17.0.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-17.0.2.jar",
          "url": "simulation-foundation-17.0.2.jar",
          "size": 36134,
          "sha512": "fceaddf81fcef5921850c8ec456fef38188c7a26379729ffda0d3d3c386e4786f290ccad13ab6a30fac03dd904f47c91d78e3206e1b95219a2f115dbb7c5d924",
          "sha256": "333a864cf521daf369d1b20ecc0ff17057277cb54e05e454b3a66bf8d7435db8",
          "sha1": "b2a2d191bf58b507ca7b8cd2e0784ea9f0f10b2f",
          "md5": "c0d13b3db7c5ad887223dafcc5b0fb5f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-17.0.2-sources.jar",
          "url": "simulation-foundation-17.0.2-sources.jar",
          "size": 8970,
          "sha512": "c6e22c62e4b432f5db7254e9f181969a62958b3736db736188f6080b135f52f020dc0a114812fae66f63e4620798e97251faa73bbe98b662fdc16d3387b7d983",
          "sha256": "cc77d89349fda4b4bddb0503e12095f2ef78fae3bc37f1b87654a8a3183e99a9",
          "sha1": "cdf5115741e0073c039c96d64cdda066f12e12b1",
          "md5": "42ce1e820730b2a3e7fef38f4ebb1d12"
        }
      ]
    }
  ]
}
