{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "17.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-17.0.2.jar",
          "url": "ftc-hardware-17.0.2.jar",
          "size": 391930,
          "sha512": "bc86a0002ed5c013030e569ccdb5022881b8d8fa6ab423430b3d2a6b9b749548a87935fd7caf5b39a5172cbce9f3ca27234bb812da96368dc96e033498b4fcb9",
          "sha256": "4a1af6dbe24334744aed8dc5da94bad19113b0f5dca1c94ed73910783e1d6f70",
          "sha1": "3fb546d179daa4eabd54cf40ded7632bb81d3c8c",
          "md5": "41568e3f2cd21e5f0df7b69d57aafefc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-17.0.2.jar",
          "url": "ftc-hardware-17.0.2.jar",
          "size": 391930,
          "sha512": "bc86a0002ed5c013030e569ccdb5022881b8d8fa6ab423430b3d2a6b9b749548a87935fd7caf5b39a5172cbce9f3ca27234bb812da96368dc96e033498b4fcb9",
          "sha256": "4a1af6dbe24334744aed8dc5da94bad19113b0f5dca1c94ed73910783e1d6f70",
          "sha1": "3fb546d179daa4eabd54cf40ded7632bb81d3c8c",
          "md5": "41568e3f2cd21e5f0df7b69d57aafefc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-17.0.2-sources.jar",
          "url": "ftc-hardware-17.0.2-sources.jar",
          "size": 147869,
          "sha512": "7adae9a6e1a61de85a0bf5cb4778346d943dbb715215fc66421fe227058b6044e0ad8caff4730842f8a883eb0816caee10c1dfe6990c017f358aecb117189601",
          "sha256": "1d98c60d86ccab140cde8a02e85284eacac64e4a37d0cfc0fac83d91ee49c8c9",
          "sha1": "7d16aa0488b3721639abcb28d19308aca6725272",
          "md5": "4bcffa6425ca2062efd13ccdaa6959e2"
        }
      ]
    }
  ]
}
