{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "12.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-12.0.0.jar",
          "url": "ftc-hardware-12.0.0.jar",
          "size": 398825,
          "sha512": "b8720a1ee74398530cc524d14f7a002edf18e3d272b870dd0526a459e8f18c0ed6bc036f8d5de8af282b793dc8d87fbca7dedb775cd3dac53986dfadceea76b1",
          "sha256": "2fb7f7dfa94df22f623ec4a325152e44ae8ef8689d43bf66f3662e0684a9c4dd",
          "sha1": "494f8015408a48ba1a0c8c28a84cfe613e4a97ed",
          "md5": "9bd38f84e4a7fe2f16d9a01375a41e49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-12.0.0.jar",
          "url": "ftc-hardware-12.0.0.jar",
          "size": 398825,
          "sha512": "b8720a1ee74398530cc524d14f7a002edf18e3d272b870dd0526a459e8f18c0ed6bc036f8d5de8af282b793dc8d87fbca7dedb775cd3dac53986dfadceea76b1",
          "sha256": "2fb7f7dfa94df22f623ec4a325152e44ae8ef8689d43bf66f3662e0684a9c4dd",
          "sha1": "494f8015408a48ba1a0c8c28a84cfe613e4a97ed",
          "md5": "9bd38f84e4a7fe2f16d9a01375a41e49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-12.0.0-sources.jar",
          "url": "ftc-hardware-12.0.0-sources.jar",
          "size": 149297,
          "sha512": "7617014b783b030ba9b84c87c9050aa44b01d377cae73894623a209c7d1b272ab44dd304f3e046926cc5161c10a65299c8d2fe9df450a3d308b520918876110a",
          "sha256": "3d4a0fb0fdbaef12205be7140ab79804b6e041c4eef3dbde711bfd152d78da6e",
          "sha1": "766b80fade79b0b0ac690995278085809b642646",
          "md5": "ede80262628632b093751e7d7da415bd"
        }
      ]
    }
  ]
}
