{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "core",
    "version": "16.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "telemetry-schema",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-16.0.0.jar",
          "url": "core-16.0.0.jar",
          "size": 1476156,
          "sha512": "ceba411e08e122a305eb3e04fc630c0b3c5b6f9f612c8d61fe7b4471b4b3f4cf9bd53f237a375ea11d6c34b7920774bfda018629d74ff9efa5cf3ac7e5e798ce",
          "sha256": "73268d15e0a06bbd383fda0c7a49775e5a5006b7083411136ccb7b24dda73c01",
          "sha1": "e35ca9601a35af7b049f5417142b122b687f6cb9",
          "md5": "3e2846f097b19b060e78a4222eddc57b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "telemetry-schema",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-16.0.0.jar",
          "url": "core-16.0.0.jar",
          "size": 1476156,
          "sha512": "ceba411e08e122a305eb3e04fc630c0b3c5b6f9f612c8d61fe7b4471b4b3f4cf9bd53f237a375ea11d6c34b7920774bfda018629d74ff9efa5cf3ac7e5e798ce",
          "sha256": "73268d15e0a06bbd383fda0c7a49775e5a5006b7083411136ccb7b24dda73c01",
          "sha1": "e35ca9601a35af7b049f5417142b122b687f6cb9",
          "md5": "3e2846f097b19b060e78a4222eddc57b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-16.0.0-sources.jar",
          "url": "core-16.0.0-sources.jar",
          "size": 391701,
          "sha512": "5828067232f7ad638487708e2f0d37e955c8073070527870fefb35ddecfd5c01e93c7d2c9f8417de44e37f6f4f8e95ba5ffc7733d955cdba37b6f274e871caf5",
          "sha256": "623399134d5e3a2bc6ae0e21785c880ddf707aae64b875bc789c5999636e02f9",
          "sha1": "b47204f780bd45869cd8e0d883f1dc357bc39586",
          "md5": "9c18286f2fc1714963a892f11bacd60c"
        }
      ]
    }
  ]
}
