{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "13.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-13.0.1.jar",
          "url": "codegen-13.0.1.jar",
          "size": 442411,
          "sha512": "988ed040b597a35227481b5c219df9788ff6e306e688b5626de1fcae52d2a7c0b86ca3e10f0df637d11b21af0a0b7ab8af7ecc2ac6ebb31eb1a229349d3712a4",
          "sha256": "0303a108cc62579031ccf72adb985e7f7582aa4307a609a6140b27c746dab7e0",
          "sha1": "bbfa8a100793bc65c21fc425bc992d9db2f0ff73",
          "md5": "00ae1c2d0069e4dab93abbde927ffb88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-13.0.1.jar",
          "url": "codegen-13.0.1.jar",
          "size": 442411,
          "sha512": "988ed040b597a35227481b5c219df9788ff6e306e688b5626de1fcae52d2a7c0b86ca3e10f0df637d11b21af0a0b7ab8af7ecc2ac6ebb31eb1a229349d3712a4",
          "sha256": "0303a108cc62579031ccf72adb985e7f7582aa4307a609a6140b27c746dab7e0",
          "sha1": "bbfa8a100793bc65c21fc425bc992d9db2f0ff73",
          "md5": "00ae1c2d0069e4dab93abbde927ffb88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-13.0.1-sources.jar",
          "url": "codegen-13.0.1-sources.jar",
          "size": 90368,
          "sha512": "cbd16312d6661e6eb8c408825be3da8f7489b227674105aa00472512d1cddd0e5773d89e7d78578cdf25f3ff25de8966fef81be1f3759bb744c8eae25ef7dbc3",
          "sha256": "f3fa46766333f710de0813cbcdf9472fa029f460b351bccf1656a93d440cdf3b",
          "sha1": "364fdbedf94c913d13e7c9d99d94c0eeedfce2f9",
          "md5": "0c8358f227b12b82a5ce4d370545a81e"
        }
      ]
    }
  ]
}
