{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "17.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.2"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "17.0.2"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "17.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-17.0.2.jar",
          "url": "codegen-17.0.2.jar",
          "size": 458997,
          "sha512": "f46b63ac1849666bde856390f3e1a8937e220434e2c32c49d2a16aaeb9058d7b102e7666aad51e2466dfeaaf278dcceffd9d8ad087a136e9672ab9a6042dcb01",
          "sha256": "81208fae0bf3627671c1b501ebee6a547dc50e76c6cedc0dc05451b5c471c122",
          "sha1": "7add07bb40fb4ec2a58477a11d4e5524c8cee974",
          "md5": "966f3673d63e6e8eb2396931c54e51e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.2"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "17.0.2"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "17.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-17.0.2.jar",
          "url": "codegen-17.0.2.jar",
          "size": 458997,
          "sha512": "f46b63ac1849666bde856390f3e1a8937e220434e2c32c49d2a16aaeb9058d7b102e7666aad51e2466dfeaaf278dcceffd9d8ad087a136e9672ab9a6042dcb01",
          "sha256": "81208fae0bf3627671c1b501ebee6a547dc50e76c6cedc0dc05451b5c471c122",
          "sha1": "7add07bb40fb4ec2a58477a11d4e5524c8cee974",
          "md5": "966f3673d63e6e8eb2396931c54e51e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-17.0.2-sources.jar",
          "url": "codegen-17.0.2-sources.jar",
          "size": 93372,
          "sha512": "afc8f3ef7ffd611ee53b003b5bb8b3650df914b67daa47152efad02325a441f1eece96d20c0760c75b2b09a64bc952c0f74de37f28f76790643b5c00fcbc0b92",
          "sha256": "382301d001d16a6567775e0f9efb767ef0fb0e526069ac315e667954238869b0",
          "sha1": "eb73e7434be850fab70363cd8f1ca0ed057b8ff9",
          "md5": "e81cb944939f54d484db75ce2df4b1aa"
        }
      ]
    }
  ]
}
