{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "19.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-19.1.3.jar",
          "url": "ftc-hardware-19.1.3.jar",
          "size": 433585,
          "sha512": "bc5bb13ddf4ac53e97e235a5b40249c25f14e719d9598f971ca68c576d78e848704a59cb46a57a9d42de34d9d3ba91fb3d631263bcb53634a7bf1dd3efd0f679",
          "sha256": "cad0aa64222a2799186d6cdf5716e4e47bef934572418ff0a94d8bebe9ae335d",
          "sha1": "7b1b8af5c1038cfb6bbbb1d29b2d96cd7a6d771e",
          "md5": "f3095b1f662a7e274eaf0a956e9360ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-19.1.3.jar",
          "url": "ftc-hardware-19.1.3.jar",
          "size": 433585,
          "sha512": "bc5bb13ddf4ac53e97e235a5b40249c25f14e719d9598f971ca68c576d78e848704a59cb46a57a9d42de34d9d3ba91fb3d631263bcb53634a7bf1dd3efd0f679",
          "sha256": "cad0aa64222a2799186d6cdf5716e4e47bef934572418ff0a94d8bebe9ae335d",
          "sha1": "7b1b8af5c1038cfb6bbbb1d29b2d96cd7a6d771e",
          "md5": "f3095b1f662a7e274eaf0a956e9360ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-19.1.3-sources.jar",
          "url": "ftc-hardware-19.1.3-sources.jar",
          "size": 165811,
          "sha512": "ba93d70e44ce7f5ebe34b5457e7fe197074178772ce32d4bb8617724098a60efdd672c977883d7340e2e5699612c416d2b49b4dfb7d70672a3d1360e56f3c79c",
          "sha256": "dd8cb3da623b2e6bcff684d41e6a7d1988fadf0827c66d0d8e446e9b234e4ce9",
          "sha1": "fe50840311ac10b8f37e358fcc1a6bbc14f6bfe6",
          "md5": "4f9daf6331405f791c4d6b8865d923ca"
        }
      ]
    }
  ]
}
