{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "17.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "17.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-17.0.1.jar",
          "url": "simulation-foundation-17.0.1.jar",
          "size": 36134,
          "sha512": "8c18e377fb003259e086d2c424636d6f854b08da59748838c8f367b70e7f52d4b88a02c1c44bc9ebff464472a21e80e437f9f8ff0af4d99a88388817ff3b4206",
          "sha256": "b614c8cd0f2fb94932ff05adc87e34a8137e7a20f2ab522c071abcf6b3250249",
          "sha1": "d31dfbcfe9b0ba8c9f3f9eaee432f8ce2e3da8e4",
          "md5": "590d7c7d319581a6a3cd9e3203ef4104"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "17.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-17.0.1.jar",
          "url": "simulation-foundation-17.0.1.jar",
          "size": 36134,
          "sha512": "8c18e377fb003259e086d2c424636d6f854b08da59748838c8f367b70e7f52d4b88a02c1c44bc9ebff464472a21e80e437f9f8ff0af4d99a88388817ff3b4206",
          "sha256": "b614c8cd0f2fb94932ff05adc87e34a8137e7a20f2ab522c071abcf6b3250249",
          "sha1": "d31dfbcfe9b0ba8c9f3f9eaee432f8ce2e3da8e4",
          "md5": "590d7c7d319581a6a3cd9e3203ef4104"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-17.0.1-sources.jar",
          "url": "simulation-foundation-17.0.1-sources.jar",
          "size": 8970,
          "sha512": "fdb2f99bd4dd13742af1725fca4063beb7bbaa87258bcc8776842c0de445400f3b66823c40fcd7a1450efca8e01ba4b79850604f2821219ee67c6da7e11e993b",
          "sha256": "b4ca93f29732919b15c0e0f7ab3de996152f1c9dfb556073c8ee2a6e2f0898ab",
          "sha1": "5e75e1798973d8a15ea4600c7183065ebcd4044d",
          "md5": "1c184f208252bbabfc70efd59fd12acf"
        }
      ]
    }
  ]
}
