{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-linux",
    "version": "19.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "19.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-19.1.1.jar",
          "url": "simulator-runtime-linux-19.1.1.jar",
          "size": 5077,
          "sha512": "35356c80d8653b2b0268483f1fb66475eec82d2aec650be5d19e7aac53ac94244f7b0ce7c441253f8309643b2d3dcb786bef720dae61ab678dd958db9754f3f7",
          "sha256": "c6324d6b127a922f9b8d5bb6d3122538d8cc7c4f04e631bdd8264aad4dcf0f10",
          "sha1": "690ac11ce8a5e936e8e2ca1ef17680924d8336c6",
          "md5": "d57ced3bcab85d30951d8db2f0453e4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "19.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-19.1.1.jar",
          "url": "simulator-runtime-linux-19.1.1.jar",
          "size": 5077,
          "sha512": "35356c80d8653b2b0268483f1fb66475eec82d2aec650be5d19e7aac53ac94244f7b0ce7c441253f8309643b2d3dcb786bef720dae61ab678dd958db9754f3f7",
          "sha256": "c6324d6b127a922f9b8d5bb6d3122538d8cc7c4f04e631bdd8264aad4dcf0f10",
          "sha1": "690ac11ce8a5e936e8e2ca1ef17680924d8336c6",
          "md5": "d57ced3bcab85d30951d8db2f0453e4e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-linux-19.1.1-sources.jar",
          "url": "simulator-runtime-linux-19.1.1-sources.jar",
          "size": 5077,
          "sha512": "c218cd0c79a6e41cd3acb7f7975c6be0c619970bbdbdc8441dc1bb22e4734ff7d7efaa0c306237e20fd1ba9a4b0ced9022deb663f834fdb60e4dfce4f1315b6c",
          "sha256": "3360a5647543cd2411400c85276cbc59b897820f3ad2f0455ff50ed829a9bc82",
          "sha1": "d19f9b6c2afbace94caf7d0283684e2748ee6c0e",
          "md5": "fe397cebe860413544f69beffbf3e8a8"
        }
      ]
    }
  ]
}
