{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "19.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-19.1.2.jar",
          "url": "simulation-foundation-19.1.2.jar",
          "size": 36134,
          "sha512": "9f2a23c0db03cb154936b9596565b8b27b473441fae8a060762156ff9664a16137432d257b0a58202e9d105362f56184822455b9ed4e8f06219da1bbc88a81a3",
          "sha256": "e1752817d62c6833080b29efed134731759d3645e4c3dc3e6c56af877618f981",
          "sha1": "ecad18399e61627db4f3e24674c7e8f1c2802605",
          "md5": "81cd7692fc5b04a4531973e6ed8f9094"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.1.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-19.1.2.jar",
          "url": "simulation-foundation-19.1.2.jar",
          "size": 36134,
          "sha512": "9f2a23c0db03cb154936b9596565b8b27b473441fae8a060762156ff9664a16137432d257b0a58202e9d105362f56184822455b9ed4e8f06219da1bbc88a81a3",
          "sha256": "e1752817d62c6833080b29efed134731759d3645e4c3dc3e6c56af877618f981",
          "sha1": "ecad18399e61627db4f3e24674c7e8f1c2802605",
          "md5": "81cd7692fc5b04a4531973e6ed8f9094"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-19.1.2-sources.jar",
          "url": "simulation-foundation-19.1.2-sources.jar",
          "size": 8970,
          "sha512": "4b67a537c488c35ceb71d98f1051ec0875fe00db24a087cc43eafe64231fc159ab3d6c93b89787d0d850076cb45355fa938650aaab1b245b7eff59deaa856d19",
          "sha256": "b7e5671445d21355eea2d92f5d0fa2a3ebe772d6a412426efce09f29dfeee398",
          "sha1": "0b61842846da38b04cb81176737b090ad5634ae1",
          "md5": "0b8e19478cef7880bb522fdf62d084b0"
        }
      ]
    }
  ]
}
