{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "telemetry-schema",
    "version": "13.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-schema-13.0.1.jar",
          "url": "telemetry-schema-13.0.1.jar",
          "size": 27720,
          "sha512": "5a16786e8fcd4c2517004d93823328679be9885fc9e27d13e5e18bdd8597a0196b1bdf588b18a7625cae8e23a28d39f98dc97e6f75e95a4e2bb3f50b157c7ee7",
          "sha256": "a7a862a3eb7dd4d66230c54f3cedbfc1f75ee8ea855770bb2a05355e825827f5",
          "sha1": "9d2228e47468558489cb6ae35b16dca81118a007",
          "md5": "083b41dc65467953fd7129cc7a2f6f0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-schema-13.0.1.jar",
          "url": "telemetry-schema-13.0.1.jar",
          "size": 27720,
          "sha512": "5a16786e8fcd4c2517004d93823328679be9885fc9e27d13e5e18bdd8597a0196b1bdf588b18a7625cae8e23a28d39f98dc97e6f75e95a4e2bb3f50b157c7ee7",
          "sha256": "a7a862a3eb7dd4d66230c54f3cedbfc1f75ee8ea855770bb2a05355e825827f5",
          "sha1": "9d2228e47468558489cb6ae35b16dca81118a007",
          "md5": "083b41dc65467953fd7129cc7a2f6f0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "telemetry-schema-13.0.1-sources.jar",
          "url": "telemetry-schema-13.0.1-sources.jar",
          "size": 6623,
          "sha512": "8e4d924bb6f07d4ed5d2d72f92a38a1f9819e27b52d55f66c1c823a41938362e76bdc0bc84085c288e9f52c9c7a6f2c7eaf9e66a42d49256842b5a29b8932daa",
          "sha256": "9ba05d3e419f8af6012858d979fed4da9c25941ffcb807765b0ce656ce9d2d12",
          "sha1": "c2ca1c8ca3923eccb87409ebcfb06bd1319fccee",
          "md5": "8c2c1aa825f8aeedad83ca96b7bb85cf"
        }
      ]
    }
  ]
}
