{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "17.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.9"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "17.0.9"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "17.0.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-17.0.9.jar",
          "url": "codegen-17.0.9.jar",
          "size": 458997,
          "sha512": "1ba35f0f5956ecd100002252478dc56e68ed81a01ec44fd84626e1afdb622ddaa9a0c844b9043605a98d61d151f9354101db96398ca7890439dad53adbf94892",
          "sha256": "bbb966b95174d9b52924be434ba798190d1859a949963a077e5524bf94621982",
          "sha1": "30a3bd73d9022e8856bfaf939b45d944e7b218cc",
          "md5": "3d5ba37e7e291fda74b38b9610c9f85d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.9"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "17.0.9"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "17.0.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-17.0.9.jar",
          "url": "codegen-17.0.9.jar",
          "size": 458997,
          "sha512": "1ba35f0f5956ecd100002252478dc56e68ed81a01ec44fd84626e1afdb622ddaa9a0c844b9043605a98d61d151f9354101db96398ca7890439dad53adbf94892",
          "sha256": "bbb966b95174d9b52924be434ba798190d1859a949963a077e5524bf94621982",
          "sha1": "30a3bd73d9022e8856bfaf939b45d944e7b218cc",
          "md5": "3d5ba37e7e291fda74b38b9610c9f85d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-17.0.9-sources.jar",
          "url": "codegen-17.0.9-sources.jar",
          "size": 93372,
          "sha512": "7bf6d93eb886d0be8f24c328d111b1eec944ae18b527fd7c4a1622024598358dd018edb6db5bdc9f6ac2fcc890b7e2f6bcce5480719c2c8cc44bd75ff24e69fc",
          "sha256": "7fd177fc69b2af8920d5f0e04e5efa3bae50f422dfb1b8c6b50c4fd0639d57bf",
          "sha1": "7750542154933e450fa55f0ff043979bae81d8b3",
          "md5": "b51fe225f1daf8236f08659f63a74f1d"
        }
      ]
    }
  ]
}
