{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "16.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-16.0.0.jar",
          "url": "codegen-16.0.0.jar",
          "size": 457882,
          "sha512": "7836d1f796a154fc99d3b6c6e43c6fd6aaae6b1e9ee99cc37a64c135ccf5d097ffc9229d62e5205644f086232795b81af5f92b44e46b99108209610834af695a",
          "sha256": "3e42efe826fd095f128f4d9951f8db91b31e9665f11f0569cf6b3d7b9e920403",
          "sha1": "099ec40a48f5ab7e93741811c9ffc31048879ad5",
          "md5": "ce3487a080e30be736643f4e2ef93013"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-16.0.0.jar",
          "url": "codegen-16.0.0.jar",
          "size": 457882,
          "sha512": "7836d1f796a154fc99d3b6c6e43c6fd6aaae6b1e9ee99cc37a64c135ccf5d097ffc9229d62e5205644f086232795b81af5f92b44e46b99108209610834af695a",
          "sha256": "3e42efe826fd095f128f4d9951f8db91b31e9665f11f0569cf6b3d7b9e920403",
          "sha1": "099ec40a48f5ab7e93741811c9ffc31048879ad5",
          "md5": "ce3487a080e30be736643f4e2ef93013"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-16.0.0-sources.jar",
          "url": "codegen-16.0.0-sources.jar",
          "size": 93002,
          "sha512": "58f9247225283dd7496f1376dc7b1f175f622e9f7d2595ea00accc1872608c04cbc112c917e874be0af5a9bf2f7d407d1cc8c2ebdaf198941c73f105c7f5013e",
          "sha256": "8fb1ee2a02893bfe0530e40c7a83a3826ec9cbb8c1a163bd54060f861a60767c",
          "sha1": "20fc4ad8226982d02fed7de4cf504894fbb5ebc1",
          "md5": "52c878dfa7b8c19ff81cacf8130585a0"
        }
      ]
    }
  ]
}
