{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "core",
    "version": "13.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "telemetry-schema",
          "version": {
            "requires": "13.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "13.0.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-13.0.0.jar",
          "url": "core-13.0.0.jar",
          "size": 1613885,
          "sha512": "e491ab7f9273599a8e8e89a81af514e5e3c5768f6d97989681cba6cc5f472cb005e5fe27767b11f4a350f2a675bdcbe82cebee0b34c58b44d6025dcceac7039d",
          "sha256": "4799292ef81da37574d57cbdd5097f36b75158a29b456829ccf57444334006b9",
          "sha1": "a729ea7493c7515d3e9d0cc8e5d0e6d570787c69",
          "md5": "b44a28c99dee4a53ca1211bf82071bd3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "telemetry-schema",
          "version": {
            "requires": "13.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "13.0.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-13.0.0.jar",
          "url": "core-13.0.0.jar",
          "size": 1613885,
          "sha512": "e491ab7f9273599a8e8e89a81af514e5e3c5768f6d97989681cba6cc5f472cb005e5fe27767b11f4a350f2a675bdcbe82cebee0b34c58b44d6025dcceac7039d",
          "sha256": "4799292ef81da37574d57cbdd5097f36b75158a29b456829ccf57444334006b9",
          "sha1": "a729ea7493c7515d3e9d0cc8e5d0e6d570787c69",
          "md5": "b44a28c99dee4a53ca1211bf82071bd3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-13.0.0-sources.jar",
          "url": "core-13.0.0-sources.jar",
          "size": 442590,
          "sha512": "29860ad2b97f0e4fc91d19df2175d9b6c06f90fba683c8c18a2b0e9bca47d241c5fb9d316187471e9bbb540a29d9a6bae4b7d9cfb3675b1170dc669dbcd21762",
          "sha256": "b084ae96e35e16a7daaf311787256630c58330bc4c95647e632fbf87fa709796",
          "sha1": "315e1f7f703cadecc6c53bdba61b268ba5bae97d",
          "md5": "e4442f0c6f8dc4940dce54405ac9e05b"
        }
      ]
    }
  ]
}
