{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-model",
    "version": "19.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-19.1.3.jar",
          "url": "project-model-19.1.3.jar",
          "size": 69518,
          "sha512": "312d4da31eadd04da393623b205ff4a88f80f76aff7cab80d1d942a49235d130fea533738babca25cad18aa561d6d42829d03769528dc1cbfd22f8010ba5837c",
          "sha256": "355ced70809536416212f31de238da19b698abdf274c83989943eb8385f4a585",
          "sha1": "66b0c112887c62cfcd47e20f5434e4dbc8845bbf",
          "md5": "18ef88e1b7df1640a30c04733c50cb3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-19.1.3.jar",
          "url": "project-model-19.1.3.jar",
          "size": 69518,
          "sha512": "312d4da31eadd04da393623b205ff4a88f80f76aff7cab80d1d942a49235d130fea533738babca25cad18aa561d6d42829d03769528dc1cbfd22f8010ba5837c",
          "sha256": "355ced70809536416212f31de238da19b698abdf274c83989943eb8385f4a585",
          "sha1": "66b0c112887c62cfcd47e20f5434e4dbc8845bbf",
          "md5": "18ef88e1b7df1640a30c04733c50cb3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-model-19.1.3-sources.jar",
          "url": "project-model-19.1.3-sources.jar",
          "size": 11758,
          "sha512": "96723cfb96fdc924e611e3a7fab52fb51f524d5d046fbbb118a42639e1cbad03b10a8888fb4a80892627ecafa9cf81473baeea427f590efca13c657f4a04067d",
          "sha256": "c0cce0e7c639943fbe70eb815d8030c50591cff4ac3e98bff4eec629616bca4d",
          "sha1": "764b3b402d64e1e08e6e5f4b3d2c4896fd76d0a8",
          "md5": "6e33b5a3021bca32c74cd1b708db79a9"
        }
      ]
    }
  ]
}
