{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "frc-runtime",
    "version": "14.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "14.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "frc-runtime-14.0.0.jar",
          "url": "frc-runtime-14.0.0.jar",
          "size": 18254,
          "sha512": "41fb63e95f8619d652e1dadd80dcb584a56a8fea4531cbe53b0eb15ab21236149f5b97cc7cf56f37c6a76f83958332bbd4ace2546346fa420d7b34ce39b06817",
          "sha256": "74a30dd9d64143c008a862526936e5ff9a8f7becb3cc0bb6bd5c978749cb507b",
          "sha1": "a7f97389e84f59e9645814c9567fbe7a89167d4f",
          "md5": "fc574e5cdcbc453d6545c2c6f4e4bf6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "14.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "frc-runtime-14.0.0.jar",
          "url": "frc-runtime-14.0.0.jar",
          "size": 18254,
          "sha512": "41fb63e95f8619d652e1dadd80dcb584a56a8fea4531cbe53b0eb15ab21236149f5b97cc7cf56f37c6a76f83958332bbd4ace2546346fa420d7b34ce39b06817",
          "sha256": "74a30dd9d64143c008a862526936e5ff9a8f7becb3cc0bb6bd5c978749cb507b",
          "sha1": "a7f97389e84f59e9645814c9567fbe7a89167d4f",
          "md5": "fc574e5cdcbc453d6545c2c6f4e4bf6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "frc-runtime-14.0.0-sources.jar",
          "url": "frc-runtime-14.0.0-sources.jar",
          "size": 9452,
          "sha512": "d5bedaf8c9f2be69b7c735e68a6ef6c3bc1262bca1d07c723b519a8d7d1d2e276c5cabb1e667799d4f32bf6bbe8a66077d0ca63f986fc9581809d018189e356d",
          "sha256": "cc1bb5b379f05d1e91e2c201fc8002825f3484b9cb590f02d8815c38cd0ac223",
          "sha1": "1ea82d0cf1ea7190d4f57bf4527a100080a242d6",
          "md5": "ac39bff616c5992d8e2e37132aef2a5c"
        }
      ]
    }
  ]
}
