{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-model",
    "version": "19.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.0.5"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "19.0.5"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-19.0.5.jar",
          "url": "project-model-19.0.5.jar",
          "size": 69518,
          "sha512": "1431ed41ea6d09f1ec928c37160d0fc0056b455d0fc779ca576ac313726ef23588081f7d97f9c09c018171ee6797a2b079d177f7d2c219c4e27a40cc876bf109",
          "sha256": "a91460c1cb8e303514228dc94adb725b36fa89106f85c26f17e36912fe9e7b63",
          "sha1": "f6b9d9627373d52e8965ea9cd191ff1480f52423",
          "md5": "0cf5bc534d55944730135a828770ce9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.0.5"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "19.0.5"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.0.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-19.0.5.jar",
          "url": "project-model-19.0.5.jar",
          "size": 69518,
          "sha512": "1431ed41ea6d09f1ec928c37160d0fc0056b455d0fc779ca576ac313726ef23588081f7d97f9c09c018171ee6797a2b079d177f7d2c219c4e27a40cc876bf109",
          "sha256": "a91460c1cb8e303514228dc94adb725b36fa89106f85c26f17e36912fe9e7b63",
          "sha1": "f6b9d9627373d52e8965ea9cd191ff1480f52423",
          "md5": "0cf5bc534d55944730135a828770ce9b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-model-19.0.5-sources.jar",
          "url": "project-model-19.0.5-sources.jar",
          "size": 11758,
          "sha512": "818e0c4fb4decabf3f7b9976ffbf357213014a4abbfcd6f190c7f68caeee10022efa3cf72c2c99760b7d57df58aa18a8b12d865c0d6b7aad56209dc59e65d8fa",
          "sha256": "a7f22373bd02d6564d666deb004872c858bda0f9b183c4d8eae28406287ce6b6",
          "sha1": "23b9cc3c1b49ef74ce7d1440c6606d61b9ef32f4",
          "md5": "1021ea37426eaffdba84185f7d7adf0b"
        }
      ]
    }
  ]
}
