{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator",
    "version": "13.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-hardware",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-mocks",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-13.0.1.jar",
          "url": "simulator-13.0.1.jar",
          "size": 201352,
          "sha512": "f863db708aaf66a2c605d5e40ee5ccb114549c59b063a61bfc15760162ed6c9d1f5956fdb3d003a5322f612b7c1313258d46d4b343ccbd32294cacd8a8aee086",
          "sha256": "6bbd6d5771856989189449b6a9ff7ff612704d3810348eb7748fe644890668cb",
          "sha1": "b28967eed89e27b4c1900d1d4d38959ae747c0b6",
          "md5": "f774ec66ab44d812376e337d8d328d2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.dyn4j",
          "module": "dyn4j",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.18"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-hardware",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-mocks",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-13.0.1.jar",
          "url": "simulator-13.0.1.jar",
          "size": 201352,
          "sha512": "f863db708aaf66a2c605d5e40ee5ccb114549c59b063a61bfc15760162ed6c9d1f5956fdb3d003a5322f612b7c1313258d46d4b343ccbd32294cacd8a8aee086",
          "sha256": "6bbd6d5771856989189449b6a9ff7ff612704d3810348eb7748fe644890668cb",
          "sha1": "b28967eed89e27b4c1900d1d4d38959ae747c0b6",
          "md5": "f774ec66ab44d812376e337d8d328d2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-13.0.1-sources.jar",
          "url": "simulator-13.0.1-sources.jar",
          "size": 70834,
          "sha512": "eb548dc4ed7b50a706dab81bb665dfc414b09f1c54608471420ca1a17a4a5ddad814e15adbc5c686820e9f26427e9dc4bc9b1d4026dd2dbc731b2442239e4980",
          "sha256": "ce96d7bf110d5336960dccad965ee27c7faac59c85c84b8fc53d10b9230ce09b",
          "sha1": "62378c1418acfa54825ed716ac0ec78fceea32ba",
          "md5": "30da7b367037e705173f94a4e6ef267d"
        }
      ]
    }
  ]
}
