{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "13.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "13.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-13.0.0.jar",
          "url": "simulation-foundation-13.0.0.jar",
          "size": 46590,
          "sha512": "45a5f23f307f49dcb999fa5505a36cd813e9f9d1ab876c3b50feb3165341a0a402d6f714c91fc0b522d05cc929f725e6e85ad8d547067a6659668ba51960bcdf",
          "sha256": "acf220f05e4d0265829823728d721a95169316c82c8eee064afc2846dd262e60",
          "sha1": "ad00ca3781c339231301b7c6257310e53392d7ba",
          "md5": "782610b2618ade14506bfbbcd5fe4f2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "13.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "13.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-13.0.0.jar",
          "url": "simulation-foundation-13.0.0.jar",
          "size": 46590,
          "sha512": "45a5f23f307f49dcb999fa5505a36cd813e9f9d1ab876c3b50feb3165341a0a402d6f714c91fc0b522d05cc929f725e6e85ad8d547067a6659668ba51960bcdf",
          "sha256": "acf220f05e4d0265829823728d721a95169316c82c8eee064afc2846dd262e60",
          "sha1": "ad00ca3781c339231301b7c6257310e53392d7ba",
          "md5": "782610b2618ade14506bfbbcd5fe4f2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-13.0.0-sources.jar",
          "url": "simulation-foundation-13.0.0-sources.jar",
          "size": 11498,
          "sha512": "9f97248d9b1e4a9acb2b6c14965bdef493125a48714fd6accda2b8dcf7116791a366cfaa309922069e83d3bff549cfd8bf4d15cae395abe43f7ef88b2e7bbc9d",
          "sha256": "48266b1df9d0d4f128f7173be49296f1b5cb61e211f0dcb099f947076cda9aea",
          "sha1": "b6cc843800d3b5a5793ba5d08d3b579c1e6b5a5e",
          "md5": "25aef8d843b00532a274afb599581cd4"
        }
      ]
    }
  ]
}
