{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "11.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-11.1.0.jar",
          "url": "ftc-hardware-11.1.0.jar",
          "size": 416319,
          "sha512": "94213f228c98b42917bcf12629391c29d6f50d37371c244da7b8f23ef1be5ab59d69a5a8c2fa9b0a781cf9101ee279ebc669feb5254bd442afee3d1b734abfe2",
          "sha256": "59296eb5172bffa4ea6642acf004f21f4ee1e081abcdacd07d4ad2d9cdbe400e",
          "sha1": "dd07bc0931d5bcd370e4e1267379872624f93e07",
          "md5": "8b6cd6642629ace3a15a44a4a68ff693"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-11.1.0.jar",
          "url": "ftc-hardware-11.1.0.jar",
          "size": 416319,
          "sha512": "94213f228c98b42917bcf12629391c29d6f50d37371c244da7b8f23ef1be5ab59d69a5a8c2fa9b0a781cf9101ee279ebc669feb5254bd442afee3d1b734abfe2",
          "sha256": "59296eb5172bffa4ea6642acf004f21f4ee1e081abcdacd07d4ad2d9cdbe400e",
          "sha1": "dd07bc0931d5bcd370e4e1267379872624f93e07",
          "md5": "8b6cd6642629ace3a15a44a4a68ff693"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-11.1.0-sources.jar",
          "url": "ftc-hardware-11.1.0-sources.jar",
          "size": 156684,
          "sha512": "86ba3ae31577bcd32490ec84e0f57d3715d540225cf8c43f2e92db5dd8ea8127119bf01dca72a1567c011ab9c1033db0ce92312831898541e2a0da528a773d67",
          "sha256": "7300edf3ef0215c600b456998dc5c352f25b72e42e09ea3285b77dca02c6160b",
          "sha1": "f59490c49af4829ec88b016c8bdf9625b43a14bc",
          "md5": "ca76d85576724f3cfa70d82757d09f2c"
        }
      ]
    }
  ]
}
