{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "core",
    "version": "15.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "telemetry-schema",
          "version": {
            "requires": "15.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "15.0.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-15.0.0.jar",
          "url": "core-15.0.0.jar",
          "size": 1469658,
          "sha512": "38cd19242ecff6be50e8f2b69853d9dc24db48699d734121654e473f48534f3a0b98a58b9f17cbd8563807ab660029bfb38fd356bf5888b74d2e5afbfbfa8fbe",
          "sha256": "f7f99d35da6dbaa0b8a85fc5b99dd4823974fe17e3c96c9bd93d7c0c71e04d13",
          "sha1": "c4ed8f701770e671edb1761f388cabd1c710e81d",
          "md5": "936dec4449ea427b4bc9686162b65081"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "telemetry-schema",
          "version": {
            "requires": "15.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "15.0.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-15.0.0.jar",
          "url": "core-15.0.0.jar",
          "size": 1469658,
          "sha512": "38cd19242ecff6be50e8f2b69853d9dc24db48699d734121654e473f48534f3a0b98a58b9f17cbd8563807ab660029bfb38fd356bf5888b74d2e5afbfbfa8fbe",
          "sha256": "f7f99d35da6dbaa0b8a85fc5b99dd4823974fe17e3c96c9bd93d7c0c71e04d13",
          "sha1": "c4ed8f701770e671edb1761f388cabd1c710e81d",
          "md5": "936dec4449ea427b4bc9686162b65081"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-15.0.0-sources.jar",
          "url": "core-15.0.0-sources.jar",
          "size": 388878,
          "sha512": "0bbe89cfd81348c1bb6eec5da20e2f6afaf5d2bceffafc7beee229219b93f61c582db2525ddb83bee00d47b3377ad311e185d5a99f252083e5d0349ce0fd9897",
          "sha256": "1e130830e229353e2fb7ed818a4bbc048180d5db4aec443e08fdf8e4c6767a74",
          "sha1": "e647663e29d14ae70dc4ef44b9f661a89a86507e",
          "md5": "79868f7a72d6149bf85a2e2e447462a7"
        }
      ]
    }
  ]
}
