{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-windows",
    "version": "19.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "19.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-19.1.3.jar",
          "url": "simulator-runtime-windows-19.1.3.jar",
          "size": 5077,
          "sha512": "3844b25e8714573945724547bc5a96aca6f4ef4767a72d4164a75a54bfa2adc7a9c6ccc43e544545b07b432d2f7c7212b386b3bcd755791131d4d6e45bd4dd3e",
          "sha256": "88fb2d2ad4e34e0bbc4ae97fabd49a9548d2a1c2d552f223f7f684f81a68d9f0",
          "sha1": "97365c001f3aa9a374ecd402eab5079162911385",
          "md5": "d7574824f1e8cafda8135deef57e5c0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-19.1.3.jar",
          "url": "simulator-runtime-windows-19.1.3.jar",
          "size": 5077,
          "sha512": "3844b25e8714573945724547bc5a96aca6f4ef4767a72d4164a75a54bfa2adc7a9c6ccc43e544545b07b432d2f7c7212b386b3bcd755791131d4d6e45bd4dd3e",
          "sha256": "88fb2d2ad4e34e0bbc4ae97fabd49a9548d2a1c2d552f223f7f684f81a68d9f0",
          "sha1": "97365c001f3aa9a374ecd402eab5079162911385",
          "md5": "d7574824f1e8cafda8135deef57e5c0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-windows-19.1.3-sources.jar",
          "url": "simulator-runtime-windows-19.1.3-sources.jar",
          "size": 5077,
          "sha512": "6046e5479098ea7f49dc2f3b917834b22edb195562e059608c5a2b5d22da239c23016da15e7501a18ee3fdd064a08cdb4f7e08a11246fb98cfdc1a8ee824e190",
          "sha256": "53c07c724dcb2ddf7a851274cef709ac7c7634e1aa7dca70f5e6ec75ff4f0e4a",
          "sha1": "890b3c3336e986bc6a2ae293ac075d7f630f86fb",
          "md5": "2f19b583809fa4ab00a35a24b1ee9c30"
        }
      ]
    }
  ]
}
