{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "19.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-19.0.4.jar",
          "url": "simulation-foundation-19.0.4.jar",
          "size": 36134,
          "sha512": "57d8147e50aabab1613449f3b14e91c132640ca2b72cdd72b5825dbf67a4232af29363c170155b997ab6199594b0cfb7aef3629d917c4396db3788cb0967a703",
          "sha256": "0b052eab4458b2dabcf511484d36c004fe294612cb1b6289cdcc56e8924870bb",
          "sha1": "182c70d6fff154aa9853ca580ca0a0d43433b23b",
          "md5": "699c3dbc74fa50c54aec87f7c0a5cd28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.0.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-19.0.4.jar",
          "url": "simulation-foundation-19.0.4.jar",
          "size": 36134,
          "sha512": "57d8147e50aabab1613449f3b14e91c132640ca2b72cdd72b5825dbf67a4232af29363c170155b997ab6199594b0cfb7aef3629d917c4396db3788cb0967a703",
          "sha256": "0b052eab4458b2dabcf511484d36c004fe294612cb1b6289cdcc56e8924870bb",
          "sha1": "182c70d6fff154aa9853ca580ca0a0d43433b23b",
          "md5": "699c3dbc74fa50c54aec87f7c0a5cd28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-19.0.4-sources.jar",
          "url": "simulation-foundation-19.0.4-sources.jar",
          "size": 8970,
          "sha512": "ce2d943d833a9663e05ff7b32b71b5ed67a8663b7f1be7c0c3300bb4fbe922fa7a0b5cd656b95c9acb7724036678b62e3dd34c762d453427de382680ec37c6b3",
          "sha256": "95425768d2ac4fe184876678afd8a6eed9cf797a86978883f2f98af6ce903b71",
          "sha1": "4ad3e2f4ec330366f131caf5b7be8ae20674172f",
          "md5": "ffaf75e1afbfe9001d44bdd46a4aaac9"
        }
      ]
    }
  ]
}
