{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-model",
    "version": "11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-11.0.0.jar",
          "url": "project-model-11.0.0.jar",
          "size": 67466,
          "sha512": "bf69f45af439059bc7d3f96db2ad7f8627158982120caac88ccfa724afc9d9726f1fe83960c665899c5ba124633a10ec2282576cad2c12187c5ecc8e0e6d2147",
          "sha256": "ff19f8098fba786ea2f08c747c8f3925a8d95a59f66472a4175fa384939d3efe",
          "sha1": "3abdf5c002561cc5b67b49a478571dee0852d0c8",
          "md5": "455323ac8d03c9876004c0c03242fa95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-11.0.0.jar",
          "url": "project-model-11.0.0.jar",
          "size": 67466,
          "sha512": "bf69f45af439059bc7d3f96db2ad7f8627158982120caac88ccfa724afc9d9726f1fe83960c665899c5ba124633a10ec2282576cad2c12187c5ecc8e0e6d2147",
          "sha256": "ff19f8098fba786ea2f08c747c8f3925a8d95a59f66472a4175fa384939d3efe",
          "sha1": "3abdf5c002561cc5b67b49a478571dee0852d0c8",
          "md5": "455323ac8d03c9876004c0c03242fa95"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-model-11.0.0-sources.jar",
          "url": "project-model-11.0.0-sources.jar",
          "size": 11765,
          "sha512": "25697670b92abfbc57bdbb72263cb6b5474b8be7c65ecdfcf4493aabef6b5daf8c45ed6aa60d92229a081f1253d4799df306cce90db49bd29f94081057113882",
          "sha256": "975228e297e10aea202975ad78afc90df1c5c148aa3283a3099c87e3f75ca560",
          "sha1": "13d648d3cd8a631464de7e9115d08f066ec65359",
          "md5": "62adb64d572def46ddfdd4d3e7c453e4"
        }
      ]
    }
  ]
}
