{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "12.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-12.0.0.jar",
          "url": "codegen-12.0.0.jar",
          "size": 442411,
          "sha512": "66fc7b08490733c5715eaabef5b09142952af50ab0c4ca1405913011c274018021e0d110ab35cf779a9ad16dd59948f0797379fded67bd54073eeb0c071e1a0c",
          "sha256": "1163612370fae06e6a179cf2d687ec155849dfc3253c8b61f03bcc5ff5775647",
          "sha1": "74a082c887b833c58b90148cb4e0878895a3f8b9",
          "md5": "4ea5ad455ba081eb597b6e6ddc0ea787"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-compiler",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-12.0.0.jar",
          "url": "codegen-12.0.0.jar",
          "size": 442411,
          "sha512": "66fc7b08490733c5715eaabef5b09142952af50ab0c4ca1405913011c274018021e0d110ab35cf779a9ad16dd59948f0797379fded67bd54073eeb0c071e1a0c",
          "sha256": "1163612370fae06e6a179cf2d687ec155849dfc3253c8b61f03bcc5ff5775647",
          "sha1": "74a082c887b833c58b90148cb4e0878895a3f8b9",
          "md5": "4ea5ad455ba081eb597b6e6ddc0ea787"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-12.0.0-sources.jar",
          "url": "codegen-12.0.0-sources.jar",
          "size": 90368,
          "sha512": "430e270e6bd398d86272131a1c8f17f35b8d5aab89b4b6bcec0b257511b4d6989bdfcd2dec2a55f130efe1ca2714acd853548674e6b043066331919feaf60468",
          "sha256": "247e1cc563fefd343254a65fc96796fa492dc075d2ee4b7b7cbea32a2e2d1882",
          "sha1": "1ca0405c394291d66beb65b5d38958ddafcd974b",
          "md5": "d58b2be96f62388d58d1b0a59f587722"
        }
      ]
    }
  ]
}
