{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-mocks",
    "version": "15.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-15.0.0.jar",
          "url": "ftc-mocks-15.0.0.jar",
          "size": 168724,
          "sha512": "e6f7ab5abb484084f7f9ca9a1ebf5f446806291f949a0a0fd8df7cd75f3a22542e8b4a15c4f0bf693f12cfa0f068ed9ea02c08322c23d55db541d0e71a5d8db6",
          "sha256": "a15e7a05921f29ddb331092dd5aa9fb4dca52713b3fbf252ee8846237a20b4e0",
          "sha1": "144154a485ab969b46a02e4ab82e66638be11124",
          "md5": "70bd15e8591b53e15d7518e7923a3e71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-15.0.0.jar",
          "url": "ftc-mocks-15.0.0.jar",
          "size": 168724,
          "sha512": "e6f7ab5abb484084f7f9ca9a1ebf5f446806291f949a0a0fd8df7cd75f3a22542e8b4a15c4f0bf693f12cfa0f068ed9ea02c08322c23d55db541d0e71a5d8db6",
          "sha256": "a15e7a05921f29ddb331092dd5aa9fb4dca52713b3fbf252ee8846237a20b4e0",
          "sha1": "144154a485ab969b46a02e4ab82e66638be11124",
          "md5": "70bd15e8591b53e15d7518e7923a3e71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-mocks-15.0.0-sources.jar",
          "url": "ftc-mocks-15.0.0-sources.jar",
          "size": 39531,
          "sha512": "864ae6d3264a87149eddda88f7ba7887913ff05db2282a3c219ef9f28b7ff1f56b2bef310d61e571d939cf3bdb92371d39fd3d458f393888995f7a41da7a1601",
          "sha256": "25cc4ab1bc6bae2294c7fd71ae1abdac46ed962fa8ceea5eb159354387b37331",
          "sha1": "8d251e5a2afc080ee34535d02d6b35e614680461",
          "md5": "d0478d645f4eeec39bbd55cd1f796081"
        }
      ]
    }
  ]
}
