{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-compiler",
    "version": "15.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "15.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "project-compiler-15.0.4.jar",
          "url": "project-compiler-15.0.4.jar",
          "size": 71976,
          "sha512": "ec1037163ef7c6768e6fcd4914d1f763ab055ad2f006d90c8863147f9a49bcef27c15da67e1e8d5dd68604df19845c56e6908729f14240d43b8e577d95235d6e",
          "sha256": "0242a514d57690ece73a0c6167e3fab4e7913501b1a21804bd91907a6dc6848e",
          "sha1": "9eb04348ac8e27bccda41b33ded2da9f3f290bfc",
          "md5": "8c683a88644d337413be98068a04c2f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "15.0.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-compiler-15.0.4.jar",
          "url": "project-compiler-15.0.4.jar",
          "size": 71976,
          "sha512": "ec1037163ef7c6768e6fcd4914d1f763ab055ad2f006d90c8863147f9a49bcef27c15da67e1e8d5dd68604df19845c56e6908729f14240d43b8e577d95235d6e",
          "sha256": "0242a514d57690ece73a0c6167e3fab4e7913501b1a21804bd91907a6dc6848e",
          "sha1": "9eb04348ac8e27bccda41b33ded2da9f3f290bfc",
          "md5": "8c683a88644d337413be98068a04c2f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-compiler-15.0.4-sources.jar",
          "url": "project-compiler-15.0.4-sources.jar",
          "size": 10327,
          "sha512": "5a9d3767e111137cf3f04483752ede0fe1810066ae5bf9365a8256cc58271283e906c6d870b885a89f4ff486f8e80a0bf2fa5ffb6ff8577a7bb87fb7edba273b",
          "sha256": "f036a4dc3a6309e7af3deaad8e6ab6ccade32c0441f1de771b8bb63a407fc96b",
          "sha1": "b0fda12f3a48d210f6e04112430241023beac680",
          "md5": "50fb5cab5b2bab9ad1ab2f03bda5d51b"
        }
      ]
    }
  ]
}
