{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "15.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-15.0.3.jar",
          "url": "ftc-hardware-15.0.3.jar",
          "size": 384375,
          "sha512": "9ef9c38d073555ae476e759996b847c02bb5fdc50c2e4f2e4e55f91879f4a603b66ccf9a3e227724d2f029d8f0c7645d9b90c5db54725d058e9fbee8bb2e89e0",
          "sha256": "413d39833bcab0f4435d4d727a1625d4f8ff37d7b80a13ae6c6c05890940f99a",
          "sha1": "4382c8456dbecae68c258ba01ae17c2ef587f28f",
          "md5": "99ca93e655bb363f01ceef9e9335ed58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-15.0.3.jar",
          "url": "ftc-hardware-15.0.3.jar",
          "size": 384375,
          "sha512": "9ef9c38d073555ae476e759996b847c02bb5fdc50c2e4f2e4e55f91879f4a603b66ccf9a3e227724d2f029d8f0c7645d9b90c5db54725d058e9fbee8bb2e89e0",
          "sha256": "413d39833bcab0f4435d4d727a1625d4f8ff37d7b80a13ae6c6c05890940f99a",
          "sha1": "4382c8456dbecae68c258ba01ae17c2ef587f28f",
          "md5": "99ca93e655bb363f01ceef9e9335ed58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-15.0.3-sources.jar",
          "url": "ftc-hardware-15.0.3-sources.jar",
          "size": 145495,
          "sha512": "396e216fd80ef3aff91d8c87c58e908e7db02f84aede490cfad85b69b40d58c15d93c902ad3c7902b84fb8898bdafa16d27c07d477162ce587b125ef14875992",
          "sha256": "c28e57864646b5b5935328052fafdb5016374a29b7fb48f6282690f69ab09015",
          "sha1": "1d33260ad676b16c080ef47e516013e9a719900c",
          "md5": "9067c74d167e862372c1476b0e3db903"
        }
      ]
    }
  ]
}
