{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-mocks",
    "version": "15.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-15.0.1.jar",
          "url": "ftc-mocks-15.0.1.jar",
          "size": 168724,
          "sha512": "2f5365e8e13a4b339769c1d13536a315c3bc04c0fcb56a39bb06386a6cfe0834fdc4a7c55875833d33df2639411b3ae2b1827ce0b8af7ba47bcd5461355318ab",
          "sha256": "e16de9c4915b18ca3e788a68e7d442fff9b750b9ae8ac021330dc2a4ea008b80",
          "sha1": "9e3bdd7aaf1ec38605d93c18430d1d196a65f202",
          "md5": "45a9a1ac1909ad7c58adae94bcee8421"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-15.0.1.jar",
          "url": "ftc-mocks-15.0.1.jar",
          "size": 168724,
          "sha512": "2f5365e8e13a4b339769c1d13536a315c3bc04c0fcb56a39bb06386a6cfe0834fdc4a7c55875833d33df2639411b3ae2b1827ce0b8af7ba47bcd5461355318ab",
          "sha256": "e16de9c4915b18ca3e788a68e7d442fff9b750b9ae8ac021330dc2a4ea008b80",
          "sha1": "9e3bdd7aaf1ec38605d93c18430d1d196a65f202",
          "md5": "45a9a1ac1909ad7c58adae94bcee8421"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-mocks-15.0.1-sources.jar",
          "url": "ftc-mocks-15.0.1-sources.jar",
          "size": 39531,
          "sha512": "dcb41894988e10924a2d5735a930898637ea622947585fe9ee4851981c1cd59c1c96b32307345d398c472615df8c6a1b205f0d30f5580c309eb80fbde2511e55",
          "sha256": "1984cd395bb2550dbac0a2513b3757b7b2f3d7dcfe572624c718416ff279b7ce",
          "sha1": "023ff339fbfb100d46a59f980aaa63e7779fd702",
          "md5": "9e571a6bea1c93cb2411828192fd8b30"
        }
      ]
    }
  ]
}
