{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "frc-runtime",
    "version": "15.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "frc-runtime-15.0.2.jar",
          "url": "frc-runtime-15.0.2.jar",
          "size": 18255,
          "sha512": "3f01b8fb29f1675feed2825c7c39ccbc396d53069f8a00728b2f4e0f3908ed71469a1d0c6b53206f02e82681c9662495ff119c4015ff96060d7e3bdf0d5b4edc",
          "sha256": "f3d58b06033dc298159c9ce14a24453a965549269524a08320653f67adc80bc9",
          "sha1": "6a3f138cff8ad26f4f6de6950b77ab1c79a94891",
          "md5": "e22235716421494e7f176f5d7ce8f834"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "frc-runtime-15.0.2.jar",
          "url": "frc-runtime-15.0.2.jar",
          "size": 18255,
          "sha512": "3f01b8fb29f1675feed2825c7c39ccbc396d53069f8a00728b2f4e0f3908ed71469a1d0c6b53206f02e82681c9662495ff119c4015ff96060d7e3bdf0d5b4edc",
          "sha256": "f3d58b06033dc298159c9ce14a24453a965549269524a08320653f67adc80bc9",
          "sha1": "6a3f138cff8ad26f4f6de6950b77ab1c79a94891",
          "md5": "e22235716421494e7f176f5d7ce8f834"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "frc-runtime-15.0.2-sources.jar",
          "url": "frc-runtime-15.0.2-sources.jar",
          "size": 9453,
          "sha512": "3abe7afc2388035293ccdf5fc42d5ddfaaa927739e017adc15b796bb5e73ad1eca15f8a01115a7b501b5efb4f59e400a2ac3a9cf58996f4e9d6c7fe3498357c9",
          "sha256": "c4b7242272b6bda97409b3d8d43cb7097ea5886b60f2a82931ad17c902a504ac",
          "sha1": "800a099caf15eb660056fc5eed32ee4786b15e7b",
          "md5": "2e41951eb68599a3df19880414acdbaa"
        }
      ]
    }
  ]
}
