{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "telemetry-schema",
    "version": "19.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-schema-19.1.3.jar",
          "url": "telemetry-schema-19.1.3.jar",
          "size": 41201,
          "sha512": "22c053842e0c9fa7421d6d653ed84a41c230a460f61d81c208b4ccd6ddc9c396d033da07348c8229cd6a94f19916a803c7b94da8561141cc679b101cb2c9cb1b",
          "sha256": "089962a9ca8b5db0130d023470fa839391c5b919df02aca8cd6b466e829ce2df",
          "sha1": "1eb2dbe9f5b5a52d1b039bbf51ecea44731d45d4",
          "md5": "4491a4aaadf6934f7e98618bbce21c0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-schema-19.1.3.jar",
          "url": "telemetry-schema-19.1.3.jar",
          "size": 41201,
          "sha512": "22c053842e0c9fa7421d6d653ed84a41c230a460f61d81c208b4ccd6ddc9c396d033da07348c8229cd6a94f19916a803c7b94da8561141cc679b101cb2c9cb1b",
          "sha256": "089962a9ca8b5db0130d023470fa839391c5b919df02aca8cd6b466e829ce2df",
          "sha1": "1eb2dbe9f5b5a52d1b039bbf51ecea44731d45d4",
          "md5": "4491a4aaadf6934f7e98618bbce21c0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "telemetry-schema-19.1.3-sources.jar",
          "url": "telemetry-schema-19.1.3-sources.jar",
          "size": 11216,
          "sha512": "82a6650ef33b879995dd7366da8059cea78e7689ea1f5c9a76717eca1d7658f03ea1f620ad1ada8b57ed7bd228be1edf7de99b7852b1872022142ccb66d5009e",
          "sha256": "8c82aa96dcd2d8ebfebd49c9ae798fafe0a3ed1c138ec0b48f3d9e45affdc8ca",
          "sha1": "1083a9ccf4a7b96fdd713ced52c8d67ac9e60026",
          "md5": "66caae6b5ab09049e756e131d4ed3859"
        }
      ]
    }
  ]
}
