{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "xrp-hardware",
    "version": "17.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "telemetry-schema",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "17.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "xrp-hardware-17.0.1.jar",
          "url": "xrp-hardware-17.0.1.jar",
          "size": 27085,
          "sha512": "423ebc5d75297849ed5289f5b7fbec7d8b013c4018031b9d62692ba65516c58a05219e9db15fc2b21ebedb3a4a4eb99cf025a50f6a87f5ad7769c374baa5be69",
          "sha256": "2dccba8e39582f3bcd81b99c6e46e1b6452001fb4ffae4ac28a6b8b53cea7a3a",
          "sha1": "18db4958c670cfbda725517a5c9e33d788146570",
          "md5": "72d34fdef768ab52eeec4c4603d71a0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "telemetry-schema",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "17.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "xrp-hardware-17.0.1.jar",
          "url": "xrp-hardware-17.0.1.jar",
          "size": 27085,
          "sha512": "423ebc5d75297849ed5289f5b7fbec7d8b013c4018031b9d62692ba65516c58a05219e9db15fc2b21ebedb3a4a4eb99cf025a50f6a87f5ad7769c374baa5be69",
          "sha256": "2dccba8e39582f3bcd81b99c6e46e1b6452001fb4ffae4ac28a6b8b53cea7a3a",
          "sha1": "18db4958c670cfbda725517a5c9e33d788146570",
          "md5": "72d34fdef768ab52eeec4c4603d71a0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xrp-hardware-17.0.1-sources.jar",
          "url": "xrp-hardware-17.0.1-sources.jar",
          "size": 9018,
          "sha512": "1af3e9af50e9e4e0cd2f9b73468fb720cc6b388bc58bccf4a449a808cffd0f92f4d34a4d5e8203cbe548a7516f7efdfd077238dbe318078e30177e8490790ec4",
          "sha256": "e1f8c83da48c54ed5213cd0f1243f8683e75286a93fa188c73ceeca4c3eaa888",
          "sha1": "055ed3d29df46ce1aa08feb032ce144bbbf8a981",
          "md5": "e6605aed1051912726a679cc9c77a4b1"
        }
      ]
    }
  ]
}
