{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-schema",
    "version": "19.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-schema-19.1.4.jar",
          "url": "project-schema-19.1.4.jar",
          "size": 668131,
          "sha512": "4cd61e7b1ecbcaeb0efb51bbab35c03cd82dc4ad1d254c44361c304a52376e15d6c808ebb878189f9112a112a4b466291e0207426f77a8efdbc812ae55998907",
          "sha256": "cc13b908ed6ddfdc1bc3fbf4e4f9657d146bc018edd32f14891d619da4636e04",
          "sha1": "333863ea09559c0c87661a715f3322aea7413e27",
          "md5": "c0fbff7ac577f4f0b8503e69725ec42e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-schema-19.1.4.jar",
          "url": "project-schema-19.1.4.jar",
          "size": 668131,
          "sha512": "4cd61e7b1ecbcaeb0efb51bbab35c03cd82dc4ad1d254c44361c304a52376e15d6c808ebb878189f9112a112a4b466291e0207426f77a8efdbc812ae55998907",
          "sha256": "cc13b908ed6ddfdc1bc3fbf4e4f9657d146bc018edd32f14891d619da4636e04",
          "sha1": "333863ea09559c0c87661a715f3322aea7413e27",
          "md5": "c0fbff7ac577f4f0b8503e69725ec42e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-schema-19.1.4-sources.jar",
          "url": "project-schema-19.1.4-sources.jar",
          "size": 96811,
          "sha512": "d5d03195ff60800980079a5e30e5b5b2e38dd25664bba9190fe922ca0f223be72cb74ce3ea0b8fa4736a2e28bf56b2b277ec39ec73fcc391250e49472b712d6b",
          "sha256": "21e1310864d2ebd407759ef3f7f397bd50af856a8421655d160d382e79920bc1",
          "sha1": "0675a17a945538f340743216386fb5ee2a38cd95",
          "md5": "cd4c197a0e95d8017676dcc9d9644f6b"
        }
      ]
    }
  ]
}
