{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-linux",
    "version": "15.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "15.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-15.0.1.jar",
          "url": "simulator-runtime-linux-15.0.1.jar",
          "size": 5077,
          "sha512": "d8470aaee32011de40c1ab2838d23a758f49374f886c7ef9511ec1ba0911a31c19ff4103234595d120ca59649d01998398ef861e0845e1f923a8218e13ad494f",
          "sha256": "54320f8d0af6ca7e91eefce26b2479145ae1de98be735f2b7a6baab282aba111",
          "sha1": "5de27892d0544704d1b0edc5c1a84ff59a931f48",
          "md5": "d710bbf3fc8e79eb27773bcb1b45a3e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "15.0.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-15.0.1.jar",
          "url": "simulator-runtime-linux-15.0.1.jar",
          "size": 5077,
          "sha512": "d8470aaee32011de40c1ab2838d23a758f49374f886c7ef9511ec1ba0911a31c19ff4103234595d120ca59649d01998398ef861e0845e1f923a8218e13ad494f",
          "sha256": "54320f8d0af6ca7e91eefce26b2479145ae1de98be735f2b7a6baab282aba111",
          "sha1": "5de27892d0544704d1b0edc5c1a84ff59a931f48",
          "md5": "d710bbf3fc8e79eb27773bcb1b45a3e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-linux-15.0.1-sources.jar",
          "url": "simulator-runtime-linux-15.0.1-sources.jar",
          "size": 5077,
          "sha512": "d1fbdc8ca0349cc7915e90e641d270a7138bf04a15946da788285dd84c4e57b5c8192a07ed867d181d495ede985d01d7d77152b42ad1cdc380cb8b5b1d516cef",
          "sha256": "54f48a902ce7d81c0dca38cbca57c52ded6a176e88e257ddeb4c99aa66b86cda",
          "sha1": "e291dcd84aa256bd50efea7889510fe026a627f1",
          "md5": "1d4b3533c53998f5c34b82da1cdf7d40"
        }
      ]
    }
  ]
}
