{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "11.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "11.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-11.1.0.jar",
          "url": "simulation-foundation-11.1.0.jar",
          "size": 46590,
          "sha512": "f53c060422d2f04a5d0cc164a4126014661ec0862e716c662f214b9a4931c31400c6cd52eddf5f1919c194e562137f8e88a9fd12f480eca170aa3eabeb36ecba",
          "sha256": "5e3e24c1cd8b22429def1e86721c53c9349343fe13cd9908c83a156ba6f5fec5",
          "sha1": "f75e9a07cff23c53dba113fa9d1545d67b062f67",
          "md5": "638777da5d9d76fd56c4dac3859c1d79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "11.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-11.1.0.jar",
          "url": "simulation-foundation-11.1.0.jar",
          "size": 46590,
          "sha512": "f53c060422d2f04a5d0cc164a4126014661ec0862e716c662f214b9a4931c31400c6cd52eddf5f1919c194e562137f8e88a9fd12f480eca170aa3eabeb36ecba",
          "sha256": "5e3e24c1cd8b22429def1e86721c53c9349343fe13cd9908c83a156ba6f5fec5",
          "sha1": "f75e9a07cff23c53dba113fa9d1545d67b062f67",
          "md5": "638777da5d9d76fd56c4dac3859c1d79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-11.1.0-sources.jar",
          "url": "simulation-foundation-11.1.0-sources.jar",
          "size": 11498,
          "sha512": "30792a9a6bba2b9723764e813b55b7f7eb9e8c28932b9a4926b542380592fe21038e52afa3065ec41cedb43230be0377af10a0856ecdb9e186ff5f4337f33724",
          "sha256": "64f7781d7f4dc09f109675fda7ce4272314211d11ef1c2946861aedadc321373",
          "sha1": "681c15b6b991071c0baee35b540c9c5dbd5f8caa",
          "md5": "9feaee72fab16731eeacd919bbd90065"
        }
      ]
    }
  ]
}
