{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-model",
    "version": "19.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.0.4"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "19.0.4"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-19.0.4.jar",
          "url": "project-model-19.0.4.jar",
          "size": 69518,
          "sha512": "1b79dda1dfa9c720353be1a88980e575bd21d9bdb44a1fea871b2213d54b17e2f6b5088b6513842ed993d36d4565ba0ded1aa5468a27db8a4f36cfd7133b427c",
          "sha256": "54b4551a4ec69c9c7ea5e7be4f3b23734a9d89c957ae0832f4652e21b981c8d4",
          "sha1": "edadc3a50829fb1be8a29ab7dbeb1c9433c23194",
          "md5": "6b0cd4f478d9b1388eed55cadafaacc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.0.4"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "19.0.4"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.0.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-19.0.4.jar",
          "url": "project-model-19.0.4.jar",
          "size": 69518,
          "sha512": "1b79dda1dfa9c720353be1a88980e575bd21d9bdb44a1fea871b2213d54b17e2f6b5088b6513842ed993d36d4565ba0ded1aa5468a27db8a4f36cfd7133b427c",
          "sha256": "54b4551a4ec69c9c7ea5e7be4f3b23734a9d89c957ae0832f4652e21b981c8d4",
          "sha1": "edadc3a50829fb1be8a29ab7dbeb1c9433c23194",
          "md5": "6b0cd4f478d9b1388eed55cadafaacc1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-model-19.0.4-sources.jar",
          "url": "project-model-19.0.4-sources.jar",
          "size": 11758,
          "sha512": "d31e01bbb3826c3b774a418020a3917c4bb2fe66bcd2de396b19bae0c9766a3c3e8343b4232f1cbafef1d5391f9713d82377573dd6f0ec653508ff478e29dd81",
          "sha256": "6b95d436dc57cd407bd09ac78ac539913189b4f3d840e0c79d687479426bab3d",
          "sha1": "5a44e0b503f238e3aa1e54a33d8f2a15ed2cad95",
          "md5": "69b7931866f02fc708f651cb52d13565"
        }
      ]
    }
  ]
}
