{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "15.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "15.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-15.0.4.jar",
          "url": "simulation-foundation-15.0.4.jar",
          "size": 36134,
          "sha512": "cadda32a240fda27e209c491018ccc42935223a291ad9c4f0debef9ef37e91b83d2743bed0de7a1dec097cdf01414d97dbfe46a6c312ff225fc9a561523e6c6e",
          "sha256": "a4835c70a564b194d379dcade64e2944062fe3062432ef73e24f6bac331e6904",
          "sha1": "1c153ac56d24557441f4533c1bef62bc0e5fee33",
          "md5": "9b42f807f65a1689d0b5b549405adf7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "15.0.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-15.0.4.jar",
          "url": "simulation-foundation-15.0.4.jar",
          "size": 36134,
          "sha512": "cadda32a240fda27e209c491018ccc42935223a291ad9c4f0debef9ef37e91b83d2743bed0de7a1dec097cdf01414d97dbfe46a6c312ff225fc9a561523e6c6e",
          "sha256": "a4835c70a564b194d379dcade64e2944062fe3062432ef73e24f6bac331e6904",
          "sha1": "1c153ac56d24557441f4533c1bef62bc0e5fee33",
          "md5": "9b42f807f65a1689d0b5b549405adf7a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-15.0.4-sources.jar",
          "url": "simulation-foundation-15.0.4-sources.jar",
          "size": 8970,
          "sha512": "a35043ca0d35d7078677cf972ca98ae3a6aa130d04a0cfaa5f2a539798a0e0240b4a7496c84740dab8dc46eb5e2cbdb8334551f468300e65efdc313cf99e9eb0",
          "sha256": "b18611d26f481d9542e7a1b1f50d30056fbbb8a57051977b0a6f08fe550e63a9",
          "sha1": "c56da626ea6105f56133cce8a6d37c914ad8bcd8",
          "md5": "fcec68c649817a4ebfb758f9610c4999"
        }
      ]
    }
  ]
}
