{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-compiler",
    "version": "11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "project-compiler-11.0.0.jar",
          "url": "project-compiler-11.0.0.jar",
          "size": 72124,
          "sha512": "ab0d98eea124b009799a6f79f0392d783e58e10e6cdfaa6d577c16a1030fb80d8dcf2e43100a02bc88187e4419020d7910cfdff60556ae4d060308b009850070",
          "sha256": "aba174c489fd14265c78e93c360fd971c0d3f01af479bfd9eb087730daac3ab9",
          "sha1": "83878c16bfd06323b969bebca0a26ad23203c458",
          "md5": "5b5013d2040cbea8a6aacecb41d4cb8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-model",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-compiler-11.0.0.jar",
          "url": "project-compiler-11.0.0.jar",
          "size": 72124,
          "sha512": "ab0d98eea124b009799a6f79f0392d783e58e10e6cdfaa6d577c16a1030fb80d8dcf2e43100a02bc88187e4419020d7910cfdff60556ae4d060308b009850070",
          "sha256": "aba174c489fd14265c78e93c360fd971c0d3f01af479bfd9eb087730daac3ab9",
          "sha1": "83878c16bfd06323b969bebca0a26ad23203c458",
          "md5": "5b5013d2040cbea8a6aacecb41d4cb8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-compiler-11.0.0-sources.jar",
          "url": "project-compiler-11.0.0-sources.jar",
          "size": 10318,
          "sha512": "e67fc3d26b98f995adbed937f3c68c5ee04209394f75811c5cd2b328943d609a6752380d6b063fddc5f5a7594940880aec7d43a7db192109207d9183b901fac2",
          "sha256": "555941d169260fbcafcb7c3f5bcb0d693c7c5742c52fe01502eabd07672a7565",
          "sha1": "aee2c1dc64396c4b9a32bff88fc7c1a785a96291",
          "md5": "80c2a9139279dbd67669ce355aa58722"
        }
      ]
    }
  ]
}
