{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-mocks",
    "version": "19.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-19.1.3.jar",
          "url": "ftc-mocks-19.1.3.jar",
          "size": 178110,
          "sha512": "7640424c78c5d991e682d50e6fbd79740b4ba5e54207f8a620326fb10f5e29d1baac48135d6cb82759eb91dca806b29fc93a4ca489026e6a16c0db5cebf75054",
          "sha256": "b702598dbfec346b01aadc02a0e5817a78ca86226e70e12b224672d09f1eee0b",
          "sha1": "a598dc7251ce46f69c9f1b5c06f39824025b8485",
          "md5": "e664277f8febd66a44e7ec5bd5b5d1e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-19.1.3.jar",
          "url": "ftc-mocks-19.1.3.jar",
          "size": 178110,
          "sha512": "7640424c78c5d991e682d50e6fbd79740b4ba5e54207f8a620326fb10f5e29d1baac48135d6cb82759eb91dca806b29fc93a4ca489026e6a16c0db5cebf75054",
          "sha256": "b702598dbfec346b01aadc02a0e5817a78ca86226e70e12b224672d09f1eee0b",
          "sha1": "a598dc7251ce46f69c9f1b5c06f39824025b8485",
          "md5": "e664277f8febd66a44e7ec5bd5b5d1e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-mocks-19.1.3-sources.jar",
          "url": "ftc-mocks-19.1.3-sources.jar",
          "size": 48665,
          "sha512": "dda2656c495bab13455c47cb2f3edbf92e481eb8ca75777d4378c00f7ae3a5f1e2647226bd3a4552212007239fce633b5e9b15bc07038ae08078be7ca49c8cc9",
          "sha256": "60049d58e9d68463ffa48afdd4e50464e2d0bede482eab74d2aea483813ea47a",
          "sha1": "446f575e7a9c6c2f8b6b8150d4a754de3f4bfc3f",
          "md5": "659e835a38cadd3bed77c18cd5d15025"
        }
      ]
    }
  ]
}
