{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "frc-runtime",
    "version": "19.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "frc-runtime-19.1.2.jar",
          "url": "frc-runtime-19.1.2.jar",
          "size": 18305,
          "sha512": "e9a6ea975eca82c1dd2bc5f3d32120f8bfa71e81341b0ee2868af50db1916cf59069a5dcef68b081ceab7f3f0827145d17ee1281bc37d4558df13468bd68c95d",
          "sha256": "2c8c41340317e7054514c4e4505ce8e4d2fe28e08521b7709a8d159b574156ae",
          "sha1": "8f4225e63835cd75f8a01b372e04f224b056ead5",
          "md5": "3f75b21d6a9b758284e9e9232af564b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "frc-runtime-19.1.2.jar",
          "url": "frc-runtime-19.1.2.jar",
          "size": 18305,
          "sha512": "e9a6ea975eca82c1dd2bc5f3d32120f8bfa71e81341b0ee2868af50db1916cf59069a5dcef68b081ceab7f3f0827145d17ee1281bc37d4558df13468bd68c95d",
          "sha256": "2c8c41340317e7054514c4e4505ce8e4d2fe28e08521b7709a8d159b574156ae",
          "sha1": "8f4225e63835cd75f8a01b372e04f224b056ead5",
          "md5": "3f75b21d6a9b758284e9e9232af564b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "frc-runtime-19.1.2-sources.jar",
          "url": "frc-runtime-19.1.2-sources.jar",
          "size": 9504,
          "sha512": "8687ece4abe21ca0b867b74920e91be2308d9c2afa5843b81cd1db1762658ce86717293c20398d89a221fe4f9bd22d9584e639617fef288aac7826b0c45dc7c6",
          "sha256": "94ec94d3ea9eb6c66d79de0cb0191e8bf0588afc623e2ba25387e4fdb0010cb3",
          "sha1": "11cd52dd2ba1ba0ee73ea0283fe5eb425c1fdcd6",
          "md5": "e05a63b941ffdbc5a8df9f349d25d07b"
        }
      ]
    }
  ]
}
