{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "core",
    "version": "11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-11.0.0.jar",
          "url": "core-11.0.0.jar",
          "size": 1630688,
          "sha512": "c7026e63bd99a539d69f74d88609a34177f440a5892b7628314dbe610c7082cd2f4a54e5addd5976b0fd24c7cb1523d277dd4bb078d06fcaaa3eba9fd1c15af6",
          "sha256": "558cdadefd837cc6fffff89caecfcf518214aa45eb789c992467de7787725ca3",
          "sha1": "f874f1205dd68f9a7a618820a04f205c3b360afe",
          "md5": "7d06a56a9e7d37fda05f63bc3ab307e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-11.0.0.jar",
          "url": "core-11.0.0.jar",
          "size": 1630688,
          "sha512": "c7026e63bd99a539d69f74d88609a34177f440a5892b7628314dbe610c7082cd2f4a54e5addd5976b0fd24c7cb1523d277dd4bb078d06fcaaa3eba9fd1c15af6",
          "sha256": "558cdadefd837cc6fffff89caecfcf518214aa45eb789c992467de7787725ca3",
          "sha1": "f874f1205dd68f9a7a618820a04f205c3b360afe",
          "md5": "7d06a56a9e7d37fda05f63bc3ab307e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-11.0.0-sources.jar",
          "url": "core-11.0.0-sources.jar",
          "size": 446987,
          "sha512": "ba48743d0269c2536111790701aa94a40209c5937535ab906bbc7c38c3e1114468238d0d947aaca6ae168acb08ecf5552f19c392429b25171e062c07143dc9da",
          "sha256": "9137695b122404a14f40c22e567f4f94d5b9583f3878e32e40c48481182e1dc2",
          "sha1": "ac812e8448c7457cdcea53892382dfcf15331ee2",
          "md5": "eccf79f9765e54848cfb5651ec3cb1ca"
        }
      ]
    }
  ]
}
