{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-schema",
    "version": "13.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-schema-13.0.1.jar",
          "url": "project-schema-13.0.1.jar",
          "size": 616235,
          "sha512": "ff869a829327edd2eec897b93c69e098c09dd987b210caf314885efdb68ac1254266a2c4e15a09df2b484c0e9176e68af798550f0dbcae23c43173f2a5d11e49",
          "sha256": "7a9b2c731cc5ad7472c770282e994c7a241a70c92b5de7250b355cc214965a06",
          "sha1": "66156441827d78bf0909cf831ae9c37b98310993",
          "md5": "aca9b7859cfa52bea939f7371e46bb21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-schema-13.0.1.jar",
          "url": "project-schema-13.0.1.jar",
          "size": 616235,
          "sha512": "ff869a829327edd2eec897b93c69e098c09dd987b210caf314885efdb68ac1254266a2c4e15a09df2b484c0e9176e68af798550f0dbcae23c43173f2a5d11e49",
          "sha256": "7a9b2c731cc5ad7472c770282e994c7a241a70c92b5de7250b355cc214965a06",
          "sha1": "66156441827d78bf0909cf831ae9c37b98310993",
          "md5": "aca9b7859cfa52bea939f7371e46bb21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-schema-13.0.1-sources.jar",
          "url": "project-schema-13.0.1-sources.jar",
          "size": 84698,
          "sha512": "d2a192908e022d27ba2970be2c46984445bc4182d9b4554f17d84ed097d8581be9499b66c11c2538a0064acf8fac9b9decca2f052478e45a9786776b972e0abe",
          "sha256": "8658520ea3b0ae6942dc98cd7fa688ee5d136b8c05564d9f110d574e4594d0e3",
          "sha1": "eb2db2896c959142d1b00a05f8d2708de3961129",
          "md5": "7a584390310a6e27bbef8d18f6931913"
        }
      ]
    }
  ]
}
