{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-mocks",
    "version": "19.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-19.1.1.jar",
          "url": "ftc-mocks-19.1.1.jar",
          "size": 178110,
          "sha512": "e68addbcceee97b686486ebadb01292f5062ee09b1d58f5dfdc930fa2f737ecb8fb54f2e659359164cafd61c87327133d3609b93c41935fa488d5f67219c3343",
          "sha256": "3f1208ae3c8be24ade70b61b0d1cdb30bbb10827809853a5fcc40543030c1c74",
          "sha1": "d6afeb4c2e683cd8358889882f4930aef5561737",
          "md5": "16c8b533e56bff2cf01ca17e186f8ac5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-19.1.1.jar",
          "url": "ftc-mocks-19.1.1.jar",
          "size": 178110,
          "sha512": "e68addbcceee97b686486ebadb01292f5062ee09b1d58f5dfdc930fa2f737ecb8fb54f2e659359164cafd61c87327133d3609b93c41935fa488d5f67219c3343",
          "sha256": "3f1208ae3c8be24ade70b61b0d1cdb30bbb10827809853a5fcc40543030c1c74",
          "sha1": "d6afeb4c2e683cd8358889882f4930aef5561737",
          "md5": "16c8b533e56bff2cf01ca17e186f8ac5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-mocks-19.1.1-sources.jar",
          "url": "ftc-mocks-19.1.1-sources.jar",
          "size": 48665,
          "sha512": "f77740e762fce41d795d97288dea5a06bed4a389cf7f7b1a98c2e9d6f138d92a8a344fd511e605c369daacb87feb0cc324e35f941724cb8370b755a7379c0a64",
          "sha256": "e8e3c507341760518d7a118b4ac9bab181f782fa03d70fce931393ae5e97047a",
          "sha1": "12b6751b2b63d7923e343405d556f639e6ee9419",
          "md5": "0a9349f7b627963bad76e1a95c5db475"
        }
      ]
    }
  ]
}
