{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "19.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-19.1.4.jar",
          "url": "simulation-foundation-19.1.4.jar",
          "size": 36134,
          "sha512": "d7a9441a4242d6dff6b975c99914aa1fc3b8be30882f3dafb1de469879926c5ee8b00dd1fde064b49fa7f992c11db54822b9a1997205b70e9a3d9456697c4992",
          "sha256": "48d07b3ac5b488c06fde9e35e49b6b44d902d525fd600777459e0957979a011c",
          "sha1": "c80b1a801cafe390743b7a4d0bdb2b4a436e215c",
          "md5": "86316d0fdc6daeb891b5646c91cc030f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "19.1.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-19.1.4.jar",
          "url": "simulation-foundation-19.1.4.jar",
          "size": 36134,
          "sha512": "d7a9441a4242d6dff6b975c99914aa1fc3b8be30882f3dafb1de469879926c5ee8b00dd1fde064b49fa7f992c11db54822b9a1997205b70e9a3d9456697c4992",
          "sha256": "48d07b3ac5b488c06fde9e35e49b6b44d902d525fd600777459e0957979a011c",
          "sha1": "c80b1a801cafe390743b7a4d0bdb2b4a436e215c",
          "md5": "86316d0fdc6daeb891b5646c91cc030f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-19.1.4-sources.jar",
          "url": "simulation-foundation-19.1.4-sources.jar",
          "size": 8970,
          "sha512": "6cfb1987083d32b0d67d713e5453738d9c1efca50217930eb67d3b1d2f313aa31781dbba1fe3eb25a25a6a3e78549219544622bc6b09c2c3d16d54c436a01dbf",
          "sha256": "346371810fe82da92ba72255716be061ce20945d8df753347d3de5367e1bc3f5",
          "sha1": "14a1f79250c2e2d7a9a26c4468677ba9458d6784",
          "md5": "65d21eb361192ed73c817c32a0d6fde8"
        }
      ]
    }
  ]
}
