{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "13.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-13.0.1.jar",
          "url": "simulation-foundation-13.0.1.jar",
          "size": 46590,
          "sha512": "fc6303b76fb1b2db0f62134338490352467a5f43950ccbbaea9e8ba64305cc18928448679299b9823d42962c1cc212f6eba51fa153c2a2f6695990b79ebe84e5",
          "sha256": "b1531509cae2db6a2b506bffa572a33323fb9f94b5b4974765aed5854207c6d5",
          "sha1": "dd6349017772cc023c0417de4bd6508f2095b703",
          "md5": "b326030f2b620d77f3d6b76ff92114e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-13.0.1.jar",
          "url": "simulation-foundation-13.0.1.jar",
          "size": 46590,
          "sha512": "fc6303b76fb1b2db0f62134338490352467a5f43950ccbbaea9e8ba64305cc18928448679299b9823d42962c1cc212f6eba51fa153c2a2f6695990b79ebe84e5",
          "sha256": "b1531509cae2db6a2b506bffa572a33323fb9f94b5b4974765aed5854207c6d5",
          "sha1": "dd6349017772cc023c0417de4bd6508f2095b703",
          "md5": "b326030f2b620d77f3d6b76ff92114e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-13.0.1-sources.jar",
          "url": "simulation-foundation-13.0.1-sources.jar",
          "size": 11498,
          "sha512": "d1f068462bd99582f8f631d747d56a34b1476000084121a973970befadf878ddd5e43692cf80efa962d827b83b0dae02b13aa233f3d9ce56979b3edf21068045",
          "sha256": "9b0d423ddce6b11806d47bbc75c728da969e3bef2d09e304c4e045084ba8d903",
          "sha1": "286ac59abd8a26ff1f67e94e042d38aa046955c3",
          "md5": "4dc4f88f863e3a38fd16354b5c6dd9d8"
        }
      ]
    }
  ]
}
