{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "19.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-19.1.2.jar",
          "url": "ftc-hardware-19.1.2.jar",
          "size": 433585,
          "sha512": "0c8d6d6ed77d314fb7333a5790416698953f52300b9fbe290e3af00863d303ca12b41a9f555a9e89491f685e4f34d29c97a1bcf108dbc5d9b0f753194b7e5a7a",
          "sha256": "31e0302c31fff9b76e998605c132931873cb12afc5fdecf3ded00e815174da18",
          "sha1": "dc1a20b4d535a26ed4fa0b13d7168bf79a99ef2c",
          "md5": "05489aa8cba39ce6a06989f3b87fd086"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "19.1.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-19.1.2.jar",
          "url": "ftc-hardware-19.1.2.jar",
          "size": 433585,
          "sha512": "0c8d6d6ed77d314fb7333a5790416698953f52300b9fbe290e3af00863d303ca12b41a9f555a9e89491f685e4f34d29c97a1bcf108dbc5d9b0f753194b7e5a7a",
          "sha256": "31e0302c31fff9b76e998605c132931873cb12afc5fdecf3ded00e815174da18",
          "sha1": "dc1a20b4d535a26ed4fa0b13d7168bf79a99ef2c",
          "md5": "05489aa8cba39ce6a06989f3b87fd086"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-19.1.2-sources.jar",
          "url": "ftc-hardware-19.1.2-sources.jar",
          "size": 165811,
          "sha512": "db7c8451dbc8f7069ef93621dd44be74b69f948cefe05cf916ca7ceedd7b5ee8fe08b89f0aca8818d0ee83b9b306e9c4b3a642df51fdef89659c9312bfd3c3ba",
          "sha256": "9cfa7e43ecbb3943ae309afc380fc5aa78a59a06f76063cc910c881c34126f8c",
          "sha1": "5e5e6fd2e47faf053335cbfd4bb50681c11fcbb5",
          "md5": "6529f28d827e193c2e579a3942c3e4d4"
        }
      ]
    }
  ]
}
