{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "frc-hardware",
    "version": "16.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "frc-runtime",
          "version": {
            "requires": "16.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "frc-hardware-16.0.1.jar",
          "url": "frc-hardware-16.0.1.jar",
          "size": 85034,
          "sha512": "831de7f5163a6dcc4c8f4e75d4f273f8b53b171b65c04a21afe2b841fa17384ed0640a4e927c92e40d525887cd8d7983bcd3572143b9a1190ec122f60165f8b1",
          "sha256": "3a74be80a90eaa2822891dcd7f08dc9f0ee3633dbea566e7eccb781415f2dcdc",
          "sha1": "f22696937dd57bffa39e04a797f473c863400931",
          "md5": "0535c929271c32ac6bb4123e643e4043"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "frc-runtime",
          "version": {
            "requires": "16.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "frc-hardware-16.0.1.jar",
          "url": "frc-hardware-16.0.1.jar",
          "size": 85034,
          "sha512": "831de7f5163a6dcc4c8f4e75d4f273f8b53b171b65c04a21afe2b841fa17384ed0640a4e927c92e40d525887cd8d7983bcd3572143b9a1190ec122f60165f8b1",
          "sha256": "3a74be80a90eaa2822891dcd7f08dc9f0ee3633dbea566e7eccb781415f2dcdc",
          "sha1": "f22696937dd57bffa39e04a797f473c863400931",
          "md5": "0535c929271c32ac6bb4123e643e4043"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "frc-hardware-16.0.1-sources.jar",
          "url": "frc-hardware-16.0.1-sources.jar",
          "size": 40419,
          "sha512": "af2f2e0de37c1654c64e0133a631154740ee7688714288c58b085462157dbf37539c6a9d20bc7acc7d2543067d6ccfdac1f2d6e664ae331f466150cb5ecbd3ce",
          "sha256": "89a80884ed6aeb85a8a1c2d321e732f4ce72d3f78ebdac161f2795da05987c9a",
          "sha1": "5a26e14d9983c6f12bb3d01279e3768dc1c9ff7e",
          "md5": "ce47053bb489b571787c5fdd2b9da962"
        }
      ]
    }
  ]
}
