{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "frc-hardware",
    "version": "15.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "frc-runtime",
          "version": {
            "requires": "15.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "frc-hardware-15.0.0.jar",
          "url": "frc-hardware-15.0.0.jar",
          "size": 85080,
          "sha512": "e53246f4edfff78b4546fdba8b51a2b6d67dab9e79ed7bddbf26d4c38199643034655c6907b521ed738fa5fabdc705713678e7de0c1f341f4148ef30587d59b4",
          "sha256": "b86456d8ad41e893b516f906427aa74aaeea0ce2ae4bf3563982a616e3044d07",
          "sha1": "3131281381e5d1991745c0b3426d73286e989a37",
          "md5": "0d184a24aca8f0c2b106f3aa13a29aa1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "frc-runtime",
          "version": {
            "requires": "15.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "frc-hardware-15.0.0.jar",
          "url": "frc-hardware-15.0.0.jar",
          "size": 85080,
          "sha512": "e53246f4edfff78b4546fdba8b51a2b6d67dab9e79ed7bddbf26d4c38199643034655c6907b521ed738fa5fabdc705713678e7de0c1f341f4148ef30587d59b4",
          "sha256": "b86456d8ad41e893b516f906427aa74aaeea0ce2ae4bf3563982a616e3044d07",
          "sha1": "3131281381e5d1991745c0b3426d73286e989a37",
          "md5": "0d184a24aca8f0c2b106f3aa13a29aa1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "frc-hardware-15.0.0-sources.jar",
          "url": "frc-hardware-15.0.0-sources.jar",
          "size": 40433,
          "sha512": "794d57a1c1e51fbc9a7cb033b95d126f6dd6d9c7e9a490546ac0f230e3bdfda033040ca40f628437eef8843480225d3b3f4544f44b0c72f0c63a6f4f7da65b31",
          "sha256": "2f27094c201ab1c8ce781ba1db96a0dc74fcae5e90c376a60e9a033efab30d03",
          "sha1": "cdc1a722546583b1d49535ca4af5aa48ef896b44",
          "md5": "601ace0a9921ee910403337fc6b9aa58"
        }
      ]
    }
  ]
}
