{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-mocks",
    "version": "15.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-15.0.4.jar",
          "url": "ftc-mocks-15.0.4.jar",
          "size": 174188,
          "sha512": "05a3e8d6a0b98374b7cf06947fdb1c13779fb1c4db171ff782958df6b241dd7ca48ec6266b120b5f133bcfb3a29e36ec321cc046c134f89058e8f57150649ba2",
          "sha256": "7d5e44feceb4cef23424150fe65c70917e1859f17ead555a5a58dddcd7f5febf",
          "sha1": "2b335ad2c20b14865966e8edbf1ef6ecc64c3012",
          "md5": "7e7841150a38e29b93f0b0102eb456d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "15.0.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-15.0.4.jar",
          "url": "ftc-mocks-15.0.4.jar",
          "size": 174188,
          "sha512": "05a3e8d6a0b98374b7cf06947fdb1c13779fb1c4db171ff782958df6b241dd7ca48ec6266b120b5f133bcfb3a29e36ec321cc046c134f89058e8f57150649ba2",
          "sha256": "7d5e44feceb4cef23424150fe65c70917e1859f17ead555a5a58dddcd7f5febf",
          "sha1": "2b335ad2c20b14865966e8edbf1ef6ecc64c3012",
          "md5": "7e7841150a38e29b93f0b0102eb456d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-mocks-15.0.4-sources.jar",
          "url": "ftc-mocks-15.0.4-sources.jar",
          "size": 40500,
          "sha512": "1c494fb44fc3f8c30e81e428026401202524eec9cb3262935560ad1889484dba8cd92988a31bac25a35b63319e0e51d802e8de2a5b72c6ed4cb10b57fbda6135",
          "sha256": "7c08e180162abb326c351cb88a756847b33619f9466e15f9937bf4317fdee2d6",
          "sha1": "2ddbc67d419600c87fd8738b5b26a61ce625f01c",
          "md5": "456a713b2e5aaf94cfabf17559f79450"
        }
      ]
    }
  ]
}
