{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "project-model",
    "version": "13.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-13.0.1.jar",
          "url": "project-model-13.0.1.jar",
          "size": 69699,
          "sha512": "927458464109fda0b1686c66d066420336842ef618adae9268007883f565872480d9f01b3b24a6b4dc68f5389bdd6ea05975a3f1313e0df0e358c9cf95019be2",
          "sha256": "cee826cde371da7fe633e8b5f7f4327de3cbbe58ca92546d1c7ec5b3769fbed6",
          "sha1": "386b405506261416e375af43c661bedd4cdcb00b",
          "md5": "4ed5ad7cfe906c2cbb26fa37ea91fbcf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "simulation-foundation",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "project-model-13.0.1.jar",
          "url": "project-model-13.0.1.jar",
          "size": 69699,
          "sha512": "927458464109fda0b1686c66d066420336842ef618adae9268007883f565872480d9f01b3b24a6b4dc68f5389bdd6ea05975a3f1313e0df0e358c9cf95019be2",
          "sha256": "cee826cde371da7fe633e8b5f7f4327de3cbbe58ca92546d1c7ec5b3769fbed6",
          "sha1": "386b405506261416e375af43c661bedd4cdcb00b",
          "md5": "4ed5ad7cfe906c2cbb26fa37ea91fbcf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "project-model-13.0.1-sources.jar",
          "url": "project-model-13.0.1-sources.jar",
          "size": 11924,
          "sha512": "cad38e8397d5f229ade8ed113f305cbd87c4ee1f652292f7c1eeaa5ad206ddc4898ebdf92a9b89d4629c661a26b10ead382e136c96abad1897101c057c1b1fb3",
          "sha256": "2f3e1bc151c3970a94d1fa0a9820b54616dd458a63b5edae7d7711f7f233def9",
          "sha1": "62e2649374b38ce5e4f345c22599db91b6d9e0c1",
          "md5": "119dfc1d5e6004dcee8644a628351bfa"
        }
      ]
    }
  ]
}
